### ISSUE TITLE
Unable to resolve read address 14000000 PC 800665c8 error

### ISSUE THREAD

**Issue by TacoBlinx** [FIX94/Nintendont#1008]
I downloaded Nintendont a couple of days ago and went through the download guide, but no matter what I did, I kept getting the same error, which leads to a blank green screen. I thought it was because of not having IOS58, but I never found a successful way to download it. (I still don't know wtf that is, everything I found is in tech lingo so I don't understand anything) I've tried re-downloading all the files, the Homebrew channel, Dolphin, even trying out other methods to get it to work, all to no avail.  Would appreciate if someone could help me out as I would like to play Mario Kart Arcade GP 2 with Mario Cards.

**Comment by carnage702** [comment]
nintendont doest work in dolphin or any emulators it will only work on real hardware because of how it works, so unless you have a real wii or wiiu it will never work.

if you have a wii or wiiu then all you need is to have the official iso58 installed and not a cios, if you have a pc only then nope nintendont is not the way.
