### ISSUE TITLE
controller only works in menu, not in games

### ISSUE THREAD

**Issue by samcambolt270** [FIX94/Nintendont#1029]
Using a mayflash ns 2, i can get menu navigation working fine, but in 99% of games, it doesnt register at all. In some games, it will register only for the 'turn on progressive mode' and 'press any button to continue' then stops immediately after that.

(8bitdo sn30 pro 2 using a wii u with forwarder)

**Comment by samcambolt270** [comment]
Using a mayflas ns 2, i can get menu navigation working fine, but in 99% of games, it doesnt register at all. iIn some games, it will register only for the 'turn on progressive mode' and 'press any button to continue' then stops immediately amter that.

**Comment by carnage702** [comment]
do you have any other controllers connected?if it works in menu ut not ingame seems to me the controller is being shafted to player2 and up and many games dont let you controll the games with player 2 and up, try checking super smash bros melee since it allows 4 players and you can see by using the hands which controller slot you are getting.
