### ISSUE TITLE
Crashes backwards compatible wii while updating titles.txt

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [FIX94/Nintendont#1043]
Model: RVL-001(USA)
Firmware: 4.3U

Loads from SD card through homebrew channel but doesn't show isos on sd card and crashes when I tell it to update titles.txt, no other storage connected just the wiis internal storage and a 32GB full size sandisk SD card, when it crashes I have to hold the power button on the console until the red light turns on.

**Comment by carnage702** [comment]
it doesnt crash its just that the internet updater means updating anything is broken so update it on your pc.

If isos dont show up is because you didnt place them in the correct folder structure.

sd:games/anyname/game.iso

the iso file needs to be called game.iso not game.iso.iso or any other name if you have hidden extensions. for example for windwaker the path to the iso would be

sd:games/windwaker/game.iso
