### ISSUE TITLE
Certain HID Controllers (Playstation,Xbox,Switch) as bluetooth controllers/More than one HID device at a time

### ISSUE THREAD

**Issue by dude98** [FIX94/Nintendont#1056]
i have a bunch of controllers, but they all require to be plugged in for them to work with nintendont. because of that, i can't play multiplayer since USB only supports one at a time, so if someone wants to use a switch pro, or a dualsense, it's back to dolphin emulator.
i just wanna be able to have the controllers connect similarly enough to bloopair where i can have for instance: P1 using Switch Pro, P2 using Xbox, P3 using a WiiU Pro, and P4 using the Gamepad, or a regular GCN controller, that way everyone can use the controller they prefer. if it's not possible, i'd love to be able to use them all plugged in at once, since i have a USB hub, so it's not like i'd run out of USB ports.
Either way, nintendont's been a great way to play gamecube games on my wii u, PSO's been great, i tried double dash lan with dolphin and it ran near perfectly, along with kirby air ride lan. and also, happy holidays to all of you.

**Comment by carnage702** [comment]
Blupair is a wiiu app, there is no way the wii has ram to run nintendont plus an app like bloopair in the background at all.
you would have to code every bt code manually inside nintendont and i dont know if anyone is willing to do that tbh. since nintendont bt stack is a mess. 

for multiple usb controllers its the same nintendont was coded to allow only one usb at a time(if you have one wiiu gc adapter you could use 4 gc controllers for instance) but its the way the hid code works, so you will have to rewrite the entire hid code to do multiple usb controllers as well and again i dont see anyone willing to do that tbh.

there is a user here that claims he did that so maybe find a way to contact him https://github.com/FIX94/Nintendont/issues/613

all in all it will not be officially added due to lack of anyone interested in doing the work sadly. you can always buy compatible bt controllers(wiiu pro controller) wiimote+classic controller, or a wiiu/switch gc adapter and some gc controllers to fill in with your usb ones you can mash them all together i use like wiiu gamepad+wiiupro+wiiu gc adapter with 2 gc controllers for 4 players lol.

**Comment by dude98** [comment]
i actually have to do that exact setup you said when i use nintendont unless i wanna use these third party gamecube controllers that feel like cheap plastic considering i got the bundle of them for 20 dollars pretty much.

also, i hope nintendont can get it's code reorganized at some point, as if this is really that baked into the code, it must suck trying to get other things working around it.
thanks for the quick response.

**Comment by dude98** [comment]
quick note, i found something interesting.
i have bloopair running through aroma, and i used the nintendont forwarder. when i had either my switch pro or dualsense turned on, they connected and stayed in a "connecting but inactive" state "i.e: the green lights on the switch pro scrolled back and forth, and the dualsesne sat with just the blue side lights on" so it sees them, and when i connected my wii u pro after them, it set them as players, just with no way to input controls, so it is running bloopair's program, even just halfway.
it might not be as far away as you thought.

**Comment by carnage702** [comment]
> quick note, i found something interesting. i have bloopair running through aroma, and i used the nintendont forwarder. when i had either my switch pro or dualsense turned on, they connected and stayed in a "connecting but inactive" state "i.e: the green lights on the switch pro scrolled back and forth, and the dualsesne sat with just the blue side lights on" so it sees them, and when i connected my wii u pro after them, it set them as players, just with no way to input controls, so it is running bloopair's program, even just halfway. it might not be as far away as you thought.

bluepair runs on another cpu core, so the core is there, vwii can only read one cpu core, the wiiu uses 3 so the stuff on the other cores are no accessible at all.
