### ISSUE TITLE
Overly bright screen vs 60FPS video for PAL GCN Game

### ISSUE THREAD

**Issue by hhabra** [FIX94/Nintendont#1057]
Hello Nintendont team,
I've started using Nintendont on an NTSC-U Wii to play the PAL version of a GCN game. While I've managed to get this working, I've run into two separate issues:

- If I play with most video mode settings (e.g. [Force, PAL50], Auto, None), the game plays at the intended 50FPS, but the screen is overly bright. From my research, this is a common problem for people with PAL systems that use NTSC cables.  For reference, I play using a Wii S-Video Cable and a Retrotink 2X Pro. 
 
- On the other hand, if the video mode setting is ([Force, MPAL], [Force, NTSC]), the screen brightness issue disappears, but the game plays at 60FPS. While in most situations that is desirable, I need my frame rate to remain at 50FPS. 

So is it possible to play a PAL GCN game on an NTSC-U Wii at the intended 50FPS, without encountering brightness issues?
Thank you for any information and help on this matter.

**Comment by carnage702** [comment]
use a component cable/hdmi converter/regular av cables instead of an s video cable? lol what do you want me to do if your using a video cable that was never meant to play pal signals? that is like using an rgb cable and then complaining pal games only show in black and white, i cant fix what the cables dont support.
