### ISSUE TITLE
[FR] support NKit format

### ISSUE THREAD

**Issue by ildar** [FIX94/Nintendont#1061]
it's a very effective compression format. E.g. Luigi's Mansion is 1.3GB in CISO format but it's NKit image is 190MB.
Some other emulators support it out of the box. So it should be doable.

**Comment by iGom** [comment]
> it's a very effective compression format. E.g. Luigi's Mansion is 1.3GB in CISO format but it's NKit image is 190MB.
> 
> Some other emulators support it out of the box. So it should be doable.

It's already supported.

**Comment by carnage702** [comment]
> > it's a very effective compression format. E.g. Luigi's Mansion is 1.3GB in CISO format but it's NKit image is 190MB.
> > Some other emulators support it out of the box. So it should be doable.
> 
> It's already supported.

its not officially supported, while many games will work with nkit many will have crash, mainly every game that uses audio streaming because nkit moves the files addressees, and the way nintendont works is those addresses cant be moved around if they use audiostreaming function or some other more exclusive hard coded  functions.



> it's a very effective compression format. E.g. Luigi's Mansion is 1.3GB in CISO format but it's NKit image is 190MB. Some other emulators support it out of the box. So it should be doable.

nkit cant be supported because
1-nintendont is not an emulator
2- nintendont cant read audiostreaming if the alignment has changed

if you want to shrink the games you can use DMTOOLBOX choose the 32k alligment option and you get a trimmed iso fully compatible with nintendont, luigi's mansion usa when trimmed with dmtoolbox is 186mb only.

**Comment by ildar** [comment]
It indeed works. Thanks a lot.

**Comment by carnage702** [comment]
> It indeed works. Thanks a lot.

luigi mansion doesnt have audiostreaming so it should be fine, same for like 80% of the games, but if you ever get a crash it has a chance it can be nkit because the game uses audiostreaming.

**Comment by ildar** [comment]
got it. Thanks a lot for your complete explanation.
