### ISSUE TITLE
Some Games work on wii, others don't. All work with Dolphin

### ISSUE THREAD

**Issue by theRTZR** [FIX94/Nintendont#1081]
Hi, 
this really drives me crazy:
Some Games work and others don't. All are detected on my hdd. USB Port is zero. Tested on my PC the roms work with dolphin without issues. All my backups are called game.iso and converted to iso correctly. I am using the latest version of USB loader Gx with the latest version of Nintendont. I use boot logos to preserve the good old look and feel of my favorite console, the GC.

Error message:
On the game cube logo screen the message is:
"The disc could not be read.  Please read the Nintendo GameCube Instruction Booklet for more information."

Example: Eternal Darkness works, F Zero Gx not 

It would be great if you have any clues how to solve this. Thx in advance.

**Comment by carnage702** [comment]
nintendont and dolphin are totally different. dolphin is an emulator, nintendont is not.

if you are getting this error is because of 2 things
1- forced settings (not all games accept the same forced settings without crashing)
2-bad iso (just because your iso works on dolphin doesnt mean it will work on nintendont, nintendont wants full 1.35gb isos with md5 matching redump to get the best compatibility.

Also never use usbloadergx when testing things, start nintendont directly from the homebrew channel and test the game from there since usbloadergx might be forcing stuff you dont even know.


So first start nintendont directly from the homebrew channel and take a picture of your nintendont settings.

**Comment by theRTZR** [comment]
![PXL_20230225_170315993 MP](https://user-images.githubusercontent.com/126246748/221369992-bb22b392-7a91-46a8-ac4f-74b7c25c6f10.jpg)
Here you go. Thanks

**Comment by carnage702** [comment]
turn force progressive to off, if f zero doesnt work still its because you have a bad iso for nintendont.

**Comment by theRTZR** [comment]
Thx I will try tomorrow and give feedback.

**Comment by carnage702** [comment]
nintendont is region free, maybe you used an ntsc ipl and renamed it to pal... you can try using skip ipl to see if the issue is with ipl

**Comment by theRTZR** [comment]
I will try on Wednesday and keep you posted.

**Comment by theRTZR** [comment]
Just tried, it was the ipls. I replaced the existing iplpal.bin version and now it is working. 

Thank you very much for helping me figuring this out and thanks to the Nintendont team for keeping childhood memories alive with this awesome piece of software. Take care and all the best for you. 

This issues can be closed.

**Comment by theRTZR** [comment]
Closed
