### ISSUE TITLE
GamePad controls

### ISSUE THREAD

**Issue by WindowsNinetyTen** [FIX94/Nintendont#1110]
Two questions:

1. How can I use the GamePad without disconnecting the GameCube controller adaptor?
2. For some reason, the A and B buttons become the B and Y buttons. How can I prevent this?

**Comment by carnage702** [comment]
1-if you want to use wiiu gamepad as player 1 just connect the gamecube controller to slot 2 and gamepad will be player one.
2-stop clicking the minus button, hitting the "-" will rotate the face buttons of wiiu gamepad/classic controller/wiiu pro controller face buttons, hitting it again will put them back in place.

**Comment by carnage702** [comment]
make sure the setting called gamepad slot is not set to 0 because if it is then its disabled.

**Comment by WindowsNinetyTen** [comment]
I tried all this, but problem persists.

**Comment by carnage702** [comment]
take a picture of your nintendont settings.

**Comment by WindowsNinetyTen** [comment]
![Nicoe](https://github.com/FIX94/Nintendont/assets/45469534/b3464e62-530a-427e-a84e-36e45cec4f9f)

**Comment by carnage702** [comment]
this arent real settings i have no idea if they are in effect or not, to actually see the real settings go through the wiiu vwii instead of doing an inject and start nintendont directly from homebrew channel and then click on settings and show me that.

**Comment by WindowsNinetyTen** [comment]
I can confirm that these settings are real and in effect. This is from Nicoe, a Nintendont config file editor.

**Comment by carnage702** [comment]
i need to see the top of the screen on actual nintendont not just the settings to confirm stuff. there is info there.

**Comment by WindowsNinetyTen** [comment]
Okay then.

**Comment by WindowsNinetyTen** [comment]
![IMG_0889](https://github.com/FIX94/Nintendont/assets/45469534/b223402e-aa90-40ce-bf76-9fc6f215d5fd)

**Comment by carnage702** [comment]
so i have been looking through the code and doing tests and this is how its coded

Hid has priority over wiiugamepad so anytime an hid usb device is connected even if its not on the same slot wiiugamepad would jump over to slot 2 which in  most games  it would be locked out ,since only player one could control the game with some exceptions like ssbm where all controller can control the game.So yeah you would need to remove your wiiugc adapter to get wiiugamepad to be player 1.

So yeah your wiiu gamepad was indeed working but it was player 2 whenever your wiiugc adapter was connected with or without gc controllers plugged in on any port.

i made some logic  fixes in 501 try it you can get the loader.dol here , jsut rename to boot.dol and replace in apps/nintendont

https://github.com/FIX94/Nintendont/raw/8b140805db8882adcc9af5d293288b3aa77da457/loader/loader.dol

**Comment by WindowsNinetyTen** [comment]
It's fixed. Thank you.
