### ISSUE TITLE
Mario Party 5 crashes with cheat code when trying to go to Party Mode

### ISSUE THREAD

**Issue by WindowsNinetyTen** [FIX94/Nintendont#1112]
After I put in a widescreen cheat code for Mario Party 5, the game crashes and whentrying to go to Party mode.

**Comment by carnage702** [comment]
not all cheatcodes are compatible with nintendont, since nintendont runs in wii mode, some adresses are not where they should be on the gamecube and so on.

Also fix94 made a custom widescreen hack for mario party games so all of them have widescreen as long as you force widescreen. obvisouly 2d  stuff cant be turned to widescreen

**Comment by WindowsNinetyTen** [comment]
Same with Mario Party 7. I guess that I shall have to resort to that. However, the other widescreen Gecko codes work perfectly for my other games, including Mario Party 4 and 6. I wonder therefore whether I could have both Cheat Codes and Force Widescreen on at the same time or whether they would conflict with each other.
I have this issue temporarily reopened so that I could ask this question without making a new thread.

**Comment by carnage702** [comment]
like i said mario party games already have a custom widescreen hack  coded in by fix94 itself so you dont need to use gecko codes you just need to force widescreen to enable the widescreen hacks this has been added since 222

https://github.com/FIX94/Nintendont/commit/cc00c799c72348fe83e57da602616bb4f09e61eb
