### ISSUE TITLE
Wii U functionality problems

### ISSUE THREAD

**Issue by game174master** [FIX94/Nintendont#1114]
out of the blue when I'm playing games with the Wii U gamepad, the A turns into X, X into Y, Y into B, and B into A. also the rumble does not work on the Wii U gamepad even when I have it turned on.

**Comment by carnage702** [comment]
first issue the buttons swapping its not an issue nor is it random, when pressing minus the face buttons swap position , pressing it again makes then go back to place, so stop pressing the minus(-) button to swap them.

Second the rumble, wiiu gamepad will never rumble on any wii inject, because nintendo themselves coded it to simulate a wii classic controller and classic controllers dont rumble so gamepad doesnt rumble in wii injects, only on wiiu native stuff and nintendont its not wiiu native, it runs in vwii mode.

**Comment by game174master** [comment]
thank you
