### ISSUE TITLE
force progressive wont work for me on mario sunshine

### ISSUE THREAD

**Issue by kamikazilucas** [FIX94/Nintendont#1116]
everytime i load the game it just runs at 480 interlaced i have force progressive on an video force ntsc on

**Comment by carnage702** [comment]
dont force progressive... mario sunshine ntsc has native progressive so dont force it just use it.

**Comment by kamikazilucas** [comment]
still saying interlaced

**Comment by carnage702** [comment]
> still saying interlaced

just put video on auto and force progressive to off, the games has native progressive, if you choose yes on the warning screen it will be progressive, more than that i cant help you, maybe your tv is seeing it wrong since the game will swap resolution on its own, nintendont if its not messing with videomodes will just follow the game ones.

**Comment by kamikazilucas** [comment]
the pal version is not progressive native

**Comment by carnage702** [comment]
> the pal version is not progressive native

of course not... only the ntsc, many pal games cant be forced to progressive or ntsc videomode, the force hacks are hacks they dont work on every game.if you want progressive, get the ntsc version.

**Comment by kamikazilucas** [comment]
well it runs progressive fine on swiss, just that the 60fps code dosent work

**Comment by carnage702** [comment]
> well it runs progressive fine on swiss, just that the 60fps code dosent work

swiss is not nintendont and vice versa.
