### ISSUE TITLE
XenoCrisis does not load

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#1123]
XenoCrisis does not load with the nintendont, going to the gc bios presentation is on a black screen.

XenoCrisis_GC_NTSC/
boot.catalog
bootldr.dol
null.dat
xenocrisis.dol

**Comment by carnage702** [comment]
Nintendont doesn't run GC homebrew and I have no idea how they built this game and with no full 1.35 gb ido to even find online I don't think it will ever work, but hey you can run the game on many other formats.

**Comment by carnage702** [comment]
Also fro, what i readed this is an **unlicensed game made using different tools than regular gc games** and since nintendont cant run homebrew code it cant run this type of games since nintendont works by patching gc patterns and functions and it wont be able to with this.

https://gbatemp.net/threads/a-real-way-to-convert-ciso-to-iso.635604/page-3#post-10210552
