### ISSUE TITLE
Issue with Nintendont

### ISSUE THREAD

**Issue by lesternygaarrd** [FIX94/Nintendont#1126]
So I homebrewed my wii a few weeks back and have been playing games successfully ever since. I have been playing Sonic Adventure 2 through Nintendont for over a week now. However, I then decided I wanted to play Chibi robo for the first time which I had downloaded also about a week ago. Downloaded it and formatted it (game.iso in folder with game name and serial number on my USB stick which is formatted to FAT32). When I went to open it it and the Nintendont was attempting to open the game, my wii froze on the screen which it was setting up all the …stuff, I’m not sure what it’s called but there is about 4 lines of stuff it starts to set up whenever you open a game for the first time it seems. 

The wii froze to the point that it couldn’t be turned off by pressing the power button on the console itself. So, I switched it off at the wall and turned it back on. Went to run Chibi robi again and opening it literally shuts my entire wii off; it just turns off. So I think, okay maybe something wrong with that file. So then I try to play Luigi’s mansion, then same thing happens, it freezes when loading up, I don’t even get to leave the Nintendont loading screens. 

So I try to load them through USB loader instead and, the wii shuts off entirely again. So I run wii games from USB loader and they are absolutely fine. Played one for over an hour there with no issues, but still issues with GameCube games. Can anyone help?

**Comment by carnage702** [comment]
you shouldnt use flash drives they are unreliable specially on nintendont if the wii is shutting off is because of 2 things 

1- check your saves folder if there are 0kb files there delete them they are corrupt save files
2- bad isos if your not using a full 1.35gb iso with md5 matching redump.org there is no garantee that the game will work, many ppl use those nkit isos and nintendont does not support them, if they work fine if they dont you need a full 1.35gb iso.

**Comment by lesternygaarrd** [comment]
I appreciate that USBs can be dodgy but I do want to see if there are issues elsewhere before going down that avenue because it’s a bit of hassle. 

Would the save folders be on Nintendont or would I need to plug the usb into a computer to access them? 
I have been downloading nkit.iso files but I put them through the gitbit programme and they seemed fine so don’t think it’s that.

**Comment by lesternygaarrd** [comment]
Also update: I have opened sonic adventure 2 and it is still running okay. Why aren’t the other games working?

**Comment by carnage702** [comment]
like i said bad isos, bad save files or imcompatible settings, im preety sure you have bad isos, just becuase an iso works in dolphin doesnt mean it will work in nintendont since nintendont is not an emulator.

First lets rule out bad isos, you will need a pc
download this
https://www.mediafire.com/file/5y3tfpoil433rij/MD5_SHA-1_Utility.exe/file

now  open this and select your iso, wait afew seconds and some numbers under md5 should appear
Now go to this website
http://redump.org/
type the name of your game and click on the correct region of your game, then look at where it says the MD5 value and copy that value, now paste that value on the program and click and it will say if the md5 match or not.
