### ISSUE TITLE
Update meta.xml from 4.431 to 6.5

### ISSUE THREAD

**Issue by playerjmr** [FIX94/Nintendont#1129]
The [meta.xml](https://github.com/FIX94/Nintendont/blob/master/nintendont/meta.xml#L5) displays an outdated version number.

**Comment by carnage702** [comment]
the meta.xml updates automatically once you launch a game in nintendont no need to manualy update it.

**Comment by playerjmr** [comment]
True, but the new open shop channel backend does not.

**Comment by carnage702** [comment]
> True, but the new open shop channel backend does not.

That's there problem then, not nintendont.

**Comment by GabubuAvailable** [comment]
that means you are lazy to manually update the version from meta.xml file...
also, consider that most of people complained about that

**Comment by carnage702** [comment]
> Well how else are they supposed to automatically retrieve the Nintendont version?

Nintendont version is always updated on the file 
https://github.com/FIX94/Nintendont/commit/8b140805db8882adcc9af5d293288b3aa77da457#diff-d183d17cec1a92756ae069f78fd634be453016eae7bea8c28d4d75f8c6822174

**Comment by DacoTaco** [comment]
normal applications (be it wii, pc, or any software application) generate the metadata once they are compiled. if you want to go a step further, you can do it based on the git tag, which makes it even more fun, easy and handy for everyone. 
this could also be done to the meta.xml too.
[even priiloader does it, partly, and its code is far from optimal or nice to look at](https://github.com/DacoTaco/priiloader/blob/master/src/priiloader/Makefile#L119-L131)  

i don't see why implementing this is not beneficial to everyone (including developers), and the whole developer industry has moved to such tactics to manage their software versions too.

can you elaborate as to why this isn't getting implemented?

**Comment by carnage702** [comment]
> normal applications (be it wii, pc, or any software application) generate the metadata once they are compiled. if you want to go a step further, you can do it based on the git tag, which makes it even more fun, easy and handy for everyone. this could also be done to the meta.xml too. [even priiloader does it, partly, and its code is far from optimal or nice to look at](https://github.com/DacoTaco/priiloader/blob/master/src/priiloader/Makefile#L119-L131)
> 
> i don't see why implementing this is not beneficial to everyone (including developers), and the whole developer industry has moved to such tactics to manage their software versions too.
> 
> can you elaborate as to why this isn't getting implemented/changed?

All main developers for nintendont are have been gone for years, I'm not a codder I can only do basic fixes here and there, I just try to maintain nintendont as best as I can, the original developers left it like that so I just follow their vision and try to make it as funcional as I can, without changing much that could break more stuff in the process.

**Comment by DacoTaco** [comment]
generating a meta.xml wouldn't break anything, as it would be done in makefile *before* the program is even compiled.
i would suggest to not close this because of your own lack of skill, but leave it open for anyone to make the changes and create a pull request for you, or others, to look at. 

or add somebody to the repo/project that can do stuff like that safely :) (not me, im way too busy and not interested)

**Comment by carnage702** [comment]
> generating a meta.xml wouldn't break anything, as it would be done in makefile _before_ the program is even compiled. i would suggest to not close this because of your own lack of skill, but leave it open for anyone to make the changes and create a pull request for you, or others, to look at.
> 
> or add somebody to the repo/project that can do stuff like that safely :) (not me, im way too busy and not interested)

Like I said before nintendont is an open source project you can fork it and make whatever you want, last time I accepted a small pull request ( Wiiu gamepad slot) seemed harmless but then people with injects on Wiiu menu lost the ability to use Wiiu gamepad and then I had to do a dirty workaround since I couldn't fix it, and the guy that made the pull request never fixed it, only months later is that someone found a fix since it was corrupting the ninconfig.bin so yeah what seems harmless causes loads of issues.

I'm following what the devs of nintendont did and I don't accept pull request that seem pointless or too specific for very small things since then, you are free to fork nintendont and do whatever you want, right now I will only accept pull request that actually impact games or fixe issues that are known, this isn't either of those cases.

**Comment by DacoTaco** [comment]
you are comparing something that has no effect on core functionality with something that does have effect on core functionality, that is unfair and not really what anyone managing a project usually does. youre blinding yourself with fear of changes.

on top of that it is also not advised to not check the landscape in which your tool lives and not accept it to evolve. the software world has changed a lot since the birth of nintendont and things like OSC ( or homebrew browser like it was called back in the day ). to not accept changes like this, is to prevent the community/user experience/code quality to become better. now, i don't have anything to do with nintendont so i have nothing to gain here mind you.

you are basically keeping Nintendont on life support, and that isn't good seeing how active the wii scene still is and how it is still changing. Take it from an experienced developer and technical lead/coach, you are making things harder on yourself and should look to empower yourself and/or make a team to handle with these kind of things if you can't.

but hey, what do i know, right?

**Comment by carnage702** [comment]
> 

Lol the issue is there is no one that wants to continue nintendont at all, I asked countless times to lots of people for help to fix games like pokemon box and such that have issues and everyone says nintendont it's too complex and they don't know how to fix it, if it wasn't for me being here in nintendont would have been stuck with a broken build where all USB controllers would crash the app, this is how nintendont was left when nobody wanted to work on it anymore, I was friend with the dev so he gave me access so I could help people on the issue page, this is the only reason why nintendont is now in stable condition. If you find people or a team that wants to continue then let me know , I'm done asking people for help on actual problems that nintendont suffers, and not just cosmetic stuff that doesn't make any difference to the actual performance off the app

**Comment by KcrPL** [comment]
Just update the meta.xml XD
