### ISSUE TITLE
Question: Possibility of putting patches like in dolphin?

### ISSUE THREAD

**Issue by FrostWolfZX** [FIX94/Nintendont#1134]
ES: Hola a todos, Tengo entendido que nintendont admite códigos de trucos gecko, pero en si quiero saber si hay alguna manera de agregar códigos de parches como en dolphin, porque?

Uso nintendont principalmente para ejecutar juegos de la placa arcade triforce, en especial para ejecutar mario kart arcade gp, y gracias a un foro en emuline obtuve códigos para desactivar el locutor de voz en el arcade gp 2 en la versión americana, pero la mayoría de los códigos solo son parches y quiero ver si puedo implementar ese código a través de nintendont.

Gracias a todos.

EN: Hello everyone, I understand that Nintendo supports gecko cheat codes, but I really want to know if there is a way to add patch codes like in Dolphin, why?

I use nintendont mainly to run games on the triforce arcade board, especially to run mario kart arcade gp, and thanks to a forum on emuline I got codes to disable the voice announcer in the arcade gp 2 in the American version, but most of The codes are only patches and I want to see if I can implement that code through Nintendo.

Thank you all.

**Comment by carnage702** [comment]
you cant streamline this, all patches must be custom to nintendont codding since some addresses are changed from gc adresses and so on, for isntance not all gecko codes that work on GC or dolphin will work on nintendont since they are patching areas where the codes was moved somewhere else do to how nintendont works, some codes work some dont and will need to find these new addresses manually.
