### ISSUE TITLE
ZSO Support

### ISSUE THREAD

**Issue by godreborn** [FIX94/Nintendont#1135]
first of all, let me inform you all that I figured out the problem with building nintendont using just the versions listed.  it's related to this file: libwinpthread-1.dll  it's missing on my normal devkitpro folder.  it may no longer be used (think it's used by the compiler), and I'm not sure how it went missing, but now I can compile nintendont perfectly fine with just those old versions.  anyway, the reason I'm here today is to to tell you that a dev friend of mine wants to add zso support to nintendont.  however, he doesn't use windows, so the old versions of devkitpro stuff are not compatible.  he needs the linux equivalent.  I built nintendont on linux just now.  works fine...except it does have that freezing problem when exiting.  I was unable to find linux versions that old, so I need some help with that.

**Comment by carnage702** [comment]
So i never used linux on my life, i cant help , unless you find so other linux users then its up to you to fix that. Also nintendont already has loads of problems with compressions that arent even compressions per say, like nkit isos and gc iso tool compressions break the audio streaming alligment which isnt an issue for dolphin but for nintendont the game will crash and so on. so yeah nintendont is full off hardcoded stuff that you cant just move freely due to wii memory management , and also a lack of ram that already goes to the maximum when saving mcemu stuff depending on the card size, so i dont see how adding another compression stuff that will probably bring more issues than solve any issues will help tbh.

gc isos are pretty damn small for today standard 1.35gb is nothing its not like ps2 games or such that can be 4+ to 8+gb games.

**Comment by godreborn** [comment]
he said zso uses lz4, and his zso reader uses very little resources.  also, even the ps1 can handle zso, so there's no doubt that the wii/wiiu can.  btw, this is Acid_Snake, the dev of ark for the psp/vita, I'm talking about.  he said he either can't build nintendont (he doesn't use windows) or he has that same issue of the freezing when exiting.  the two sites for devkitpro repositories have no linux equivalents for those versions of things.  oh, he told me that zso is handled by the ps1 cpu, even on the ps2's version.

**Comment by carnage702** [comment]
like i said i dont use linux and i think everyone that ever contributed to nintendont used windows so i dont know if there is anyone to help on that regard, also its diference reading compression on the original console itself than reading it  on a homebrew made bridge that probably had lots of gaps and its not a 1:1 read with the gc code due to memory management and stuff half emulated.

**Comment by godreborn** [comment]
well, I don't know.  I only know he's interested after ark has become quite stable.  we're going to try to start tomorrow.  he'll code it, and I'll compile.  he's on linux, which is why I asked, but he has a netbook on windows 7 w/ linux as well.  he can compile ark on it, but he had issues compiling nintendont in linux.  I can compile it, but like I said, it has that exit bug.  if you'd be willing to test the build(s), I'll post them in this issue thread.  no idea how long this takes, but he did say that it should only require 10KBs of ram.  I'll suggest he posts here, but I think he may live in Spain (not sure), so he may be asleep now.  it may be tomorrow.  I did link him to this thread.

**Comment by GerbilSoft** [comment]
Some time ago I was thinking of adding something like RVZ support to Nintendont (only with a small block size), but zstd has significantly more overhead compared to lz4. I'm not sure how common ZSO format is nowadays, though I have support for it in rom-properties for PSP disc images only at the moment. (I can extend it to GCN if/when this gets implemented.)

I haven't done much on Nintendont recently, but I can take a look at the exit bug maybe this weekend. (I have a Linux setup with the latest devkitPro tools installed.)

**Comment by godreborn** [comment]
[boot.zip](https://github.com/FIX94/Nintendont/files/12591988/boot.zip)

**Comment by godreborn** [comment]
it's finished.  please test.  pull request incoming.

**Comment by godreborn** [comment]
I may be alone in this, but solar ash is half off.  it's a game I wanted due to it being a platformer.  I gave up on this.

**Comment by carnage702** [comment]
been doing compressions and it doesnt compress?

luigi mansion trimmed  272mb compressed to zso 1,34gb
starfox daventures  trimmed 777  zso compressed 1,27gb

unless im doing something wrong the values are way off on this?

**Comment by godreborn** [comment]
it doesn't look like it's practical for that reason, but at least we tried.

**Comment by carnage702** [comment]
closing this since it makes no sense to have a compression software that doesnt even make a compression that is worthwhile while trimming is by far superior.
