### ISSUE TITLE
Wii U Pro Controller Freeze Issue

### ISSUE THREAD

**Issue by Bent3ndo** [FIX94/Nintendont#1142]
Hi,

When attempting to quit a game on Nintendont via vWii, and pressing the home button on my Wii U Pro Controller, the whole system freezes and has to be unplugged to switch off.

Am I using the wrong button to try and quit back to the menu sorry? Thanks.

**Comment by carnage702** [comment]
problem is not the controller but what you are using to start nintendont probably a cheap forwarder.

if you start nintendont from a forwarder without a full stub, nintendont can not get back to it and it will freeze.
try starting nintendont directly from the homebrew channel and then exiting, it will work since homebrew channel has a full stub to exit.
