### ISSUE TITLE
GBA-Link cable is categorized as "Will never work"

### ISSUE THREAD

**Issue by trevor403** [FIX94/Nintendont#129]
Under the section in the readme labeled "What Nintendont will never support:" the "GBA-Link cable" is listed. Yet on nintendont.com, one of the listed features is as such:

"Native Control - If set to On you can use real GameCube accessories such as the GBA-LINK..."

So why is it still listed as an impossibility? Is this a documentation error or misinformation?

**Comment by carnage702** [comment]
The reason that is shown is becuase the gba link cable only works on those old wiis with gc ports, any other wii model or wiiu wont work, so its more like a general call, but i agree that it should say

GBA link cable only works  on wii's with original gcports and the native option ON.

**Comment by FIX94** [comment]
updated it.

**Comment by SMarioMan** [comment]
Couldn't this still work with the official Wii U GameCube adapter? My understanding is that it has all of the necessary connections for it. I understand if there aren't any plans to support it in Nintendon't, but isn't it still technically feasible?

**Comment by trevor403** [comment]
It can be supported by nintendont you just have to write the config

**Comment by FIX94** [comment]
the gc adapter does NOT allow any data from the GBA, there is no buffer for it or detection built into their usb chip so again, you can forget about it.

**Comment by carnage702** [comment]
like Fix94 said several people have confirmed the Wiiu GC adapter doesnt have the components to read the gba cable signal, Crediar himself said that after looking into the adapter, there is no component made to read the gba link cable signal so even if you can plug it in it wont send in any signals which makes the feature pointless to add since you could never ever have it working on any wii or wiiu that doesnt have the GC ports to begin with, and since the gba cable already works on those wiis with GC ports then it works on all consoles that can work already, unless some third party releases a gba link to usb adapter or something(very much impossible lol)  no GC adapter can read the gba link cable signals, not myflash not nintendos.

**Comment by SMarioMan** [comment]
Thanks for all of the info guys. Sorry to bring up a dead issue.
