### ISSUE TITLE
Video issues with GC PAL BIOS on PAL Wii U

### ISSUE THREAD

**Issue by Helsionium** [FIX94/Nintendont#148]
Whenever I try to use the GC PAL BIOS on my PAL Wii U, the video glitches up like in the video linked below:

https://www.youtube.com/watch?v=XKY6G_kz2bQ

Other than the glitched video, the BIOS and games work normally, albeit slower. This does not happen when using a different BIOS, e.g. the NTSC-U BIOS, on the same PAL Wii U console. The only way to clear the glitch is to shutdown the console. Homebrew Channel and Wii System Menu "work", but without video, as they are completely covered by the glitched green and black screen.

Just for reference, the PAL BIOS file I'm using is exactly 2 MB in size and the MD5 hash is 85e7f7fdeff9fa6ecb52aa0a38cd2eb4

**Comment by carnage702** [comment]
The wiiu homebrew channel does not support the pal bios videomode its a known issue, when they coded the vwii homebrew channel they forgot to support that wierd pal videomode so there isnt much that can be done tbh.

Its listed on nintendont OP 
Do not use the GC pal Bios on wiiu.

**Comment by Helsionium** [comment]
OK thanks for clearing this up, I didn't realise that Nintendont was dependent on code outside of its developers' reach.

**Comment by GerbilSoft** [comment]
I experienced similar issues on my Wii RVL-101 when using the PAL IPL. (recent revision, somewhere after r350)

It did work correctly a while back, though there was an unpatched timer that caused the date to be far off into the future. I'll do a bisect tonight to find what version broke it.

**Comment by carnage702** [comment]
pal bios works fine on my wii, unless you got some broken pal bios becuase on the wii it always worked but not on wiiu becuase of missing videomode.

**Comment by VinsCool** [comment]
I'm wondering if a simple videopatch for pal bios would fix the problem?

**Comment by GerbilSoft** [comment]
My PAL IPL's md5sum is 85e7f7fdeff9fa6ecb52aa0a38cd2eb4, which matches the one in the original post.

I figured out what caused the actual problem. I had the Force Progressive patch enabled temporarily for one game that doesn't show an option for it. Starting a PAL GameCube game (I tested Metroid Prime, GM8P01) with Force Progressive results in the green garbage and everything running slow. (TV reports that it's 576i.) In addition, pressing the Home button causes the system to lock up.

With PAL IPL disabled and Force Progressive enabled, I get no image on screen (TV reports no signal regardless of whether or not I blindly select 60 or 50 Hz at the prompt), but the drive LED is flashing and audio plays.

I'm wondering if the issue with PAL GCN games on Wii U is similar to what the 480p patch does, since it shows the same symptoms. (Well, there's one difference; the "cube" image isn't being repeated horizontally. The only visual distortion other than slowdown are the random dots at the top and bottom of the screen.)

**Comment by carnage702** [comment]
Force progressive  bug is totaly diferent from pal bios bug,  its not even close.

Also of course force progressive breaks most pal games, force progressive only works with 60hz if it works at all so you need to force a 60hz videomode like force ntsc video and then you can try forcing progressive, but most games wont even let you force 60hz modes let alone progressive after, remenber pal games were never suposed to have progressive or 60hz modes for most of them, if you want perfect 60hz mode and progressive you should always get the ntsc version of the game.

Some games are preety hardcoded to their videomodes and wont let you change them.
