### ISSUE TITLE
WWE DOR 1&2 Random crashing

### ISSUE THREAD

**Issue by 47iscool** [FIX94/Nintendont#153]
This problem also happens on DM & Devo, both WWE Day of Reckoning games freeze.

**Comment by carnage702** [comment]
Seems like it needs some arstartdma excpetions since when its random its usualy that.
If you can test here are 2 files in each i added wwe day of rekoning games to diferent exceptions
PM is both added to the papper mario exception and nfs is added to the need for speed exception, try the nfs first since its one of those very agressive exceptions which fixes or completely breaks the game dont forget to rename the dols to boot.dol before trying.

http://www.mediafire.com/download/3syncaafm8n8ics/wweDOR.rar

**Comment by 47iscool** [comment]
Will test and let you know the results, thanks.

**Comment by 47iscool** [comment]
Still crashes with both.

**Comment by carnage702** [comment]
then the game must be really badly programed lol if it isnt arstartdma i dont know what can cause random crahes at all.

**Comment by 47iscool** [comment]
Alright thanks for checking anyway.

**Comment by FIX94** [comment]
well yea, since diosmios crashes too the game is written just too bad to help.

**Comment by 47iscool** [comment]
Seems to work fine with the limiter enabled. So it was my mistake, sorry.

**Comment by carnage702** [comment]
So all this time you were trying the game with speed limit disabled?

**Comment by 47iscool** [comment]
Yeah, but it only started working without crashing in the newest revisions.
