### ISSUE TITLE
Star Wars Rogue Squadron: Missing graphics & Glitches

### ISSUE THREAD

**Issue by adamforeman** [FIX94/Nintendont#161]
When playing the game using the latest boot.dol, graphics on both sides of the screen disappear and come back view when circling left or right. Also seems that there is an issue with transparency on some screens. I can provide stills from the TV if required.

**Comment by carnage702** [comment]
guessing your forcing widescreen?

**Comment by adamforeman** [comment]
Is that option in USB Loader GX or Nintendont or the game settings inside the game?

**Comment by carnage702** [comment]
its a nintendont option which uses an hack to make the original GCN wich runned in 4:3 to run in 16:9 for a true widescreen thing, of course its a hack so its not perfect in any sence of the word on some games it works perfectly on others it doesnt do anything on some makes objects disapear  if they are over the 4:3 mark and on some even crashes the games themselves.

if your using usbloader gx  it should have the nintendont settings there too.Since usbloader boots nintendont after you choose the game anyway, not sure if all the settings are there tough.
