### ISSUE TITLE
Gecko code type C causes freezing

### ISSUE THREAD

**Issue by 47iscool** [FIX94/Nintendont#163]
I'm not sure if anyone else has noticed this or not.

For example a code for wind waker named "puff deku leaf to go up" causes a lockup.

Here is the code:

puff deku leaf to go up [wiiztec]
C214CD5C 00000003
3C608035 6063DC58
C0030038 D01D025C
2C000000 00000000
0435DC90 C0000000
2953F580 00000019
0435DC90 41D00000
E0000000 80008000

**Comment by SevenWillis** [comment]
A lot of codes stopped working due to the re-writing of the hooks and the discontinued use of kenobiwii. It made me sad too.

**Comment by FIX94** [comment]
codes just dont work because its a wii and not a gamecube, simple as that. The codehandler used at this moment is just the extended version of the old one to support more code types. Really the only way to fix a cheat like this is to manually look into the documentation on how cheats work and then via a usb gecko read out the memory and rewrite the cheat comparing the original gamecube memory and nintendonts memory.
