### ISSUE TITLE
Using A Gamecube IPL Bios Will Corrupt A Real Memory Card

### ISSUE THREAD

**Issue by HowManyNames** [FIX94/Nintendont#187]
With memory card emulation turned off(And a 251 GC memory card in the wii), and an IPL bios, Nintendon't will load the game and bios fine, but games will complain about the memory card being corrupted, formatting the card in GCMM and then deleting the IPL bios from the game device fixes it. Hopefully a fix that allows a bios to be loaded without corrupting real GC memory cards is found.

**Comment by FIX94** [comment]
from what I hear this issue only exists with a original memory card and its not actually corrupted but the BIOS from what I hear simply cant mount the memory card properly which most likely has to do with nintendonts __CARDUnlock patch. Now if you want help for this, maybe email me the BIOS file you are using so I can (again) blindly look at it, the issue is that I dont own a original memory card so all the different __CARDUnlock patches are written blindly by me.

**Comment by HowManyNames** [comment]
The 1.2 bios works perfectly with real memory cards, so I'll just close the issue since there's a way to fix it(Downloading or dumping a different bios)
