### ISSUE TITLE
[NTSC] "Eternal Darkness: Sanity's Requiem" PS3 Select Button (may be an issue with all games) [vWii]

### ISSUE THREAD

**Issue by Auzman466** [FIX94/Nintendont#188]
I'm trying to play Eternal Darkness using Nintendont and a PS3 controller. I don't have any Nintendont settings enabled for the game except for the USB-HID option (enabled), and the PS3 controller works almost perfectly with the game except for the select button. The select button immediately freezes the game and boots back into the vWii home screen. This is an issue for me because, in just this small 20 minute opening section, I've managed to close the game on accident probably about 5 times now.
I am using the latest version of USBLoaderGX to launch the game. I believe I pressed select when I was first testing Nintendont with Ultimate Spider-Man, and it closed too.

**Comment by OTFree** [comment]
The select button on the Dualshock 3 is by default set as the home button.
On Dec 23, 2015 4:33 PM, "Auzman466" <notifications@github.com> wrote:
>
> I'm trying to play Eternal Darkness using Nintendont and a PS3 controller
I don't have any Nintendont settings enabled for the game except for the
USB-HID option (enabled), and the PS3 controller works almost perfectly
with the game except for the select button The select button immediately
freezes the game and boots back into the vWii home screen This is an issue
for me because, in just this small 20 minute opening section, I've managed
to close the game on accident probably about 5 times now
> I am using the latest version of USBLoaderGX to launch the game I believe
I pressed select when I was first testing Nintendont with Ultimate
Spider-Man, and it closed too

**Comment by Auzman466** [comment]
Is there any way to change it?

**Comment by OTFree** [comment]
To my knowledge, that would require remapping the controls manually by
messing with the control.ini file. But I'm not certain, so don't quote me
on that lol.

**Comment by Auzman466** [comment]
thanks, i'll have to try and play around with it.

**Comment by carnage702** [comment]
As people said this is not an issue at all the select is the same has the home button on a CC or wiimote, no idea how you keep pressing select lol i mean select and start are preety far appart from each other.
