### ISSUE TITLE
Wii (PAL) RGB signal - Red tint screen! (Code solution inside?)

### ISSUE THREAD

**Issue by Yamato-san** [FIX94/Nintendont#204]
Hi,

I'm using Nintendont on a PAL Wii with RGB connection (RGB Scart cable) to a CRT monitor (Sony BVM).

The Nintendont home screen as well as NTSC region games show a red tint screen. This can be avoided by forcing the NTSC games in PAL 60 Hz mode. Although not all games are fully compatible that way like the Mega Man X Collection and of course the Nintendont home screen will still have a red tint.

I would really appreciate it if Nintendont will be able to output correct PAL RGB colors in a future update.

Maybe the following will help achieving this?
The issue seems to be the very same that Artemio had with his 240p Test Suite. (http://junkerhq.net/xrgb/index.php/240p_test_suite)

I contacted Artemio and he told me that the following part of his source code solved the red tint issue with PAL RGB connection:

==========================================================

#ifdef WII_VERSION	
CONF_GetDisplayOffsetH(&OffsetH);
AspectRatio = CONF_GetAspectRatio();

/* Adjust SCART cable to output RGB and not YUV */	
if(!VIDEO_HaveComponentCable())
{
if(CONF_GetEuRGB60() > 0 || CONF_GetVideo() == CONF_VIDEO_PAL)
{
Mode_240p.viTVMode = VI_TVMODE_EURGB60_DS;
Mode_480i.viTVMode = VI_TVMODE_EURGB60_INT;	
}	
}

if(CONF_GetVideo() == CONF_VIDEO_PAL ||
CONF_GetVideo() == CONF_VIDEO_MPAL)
Options.EnablePAL = 1;	
#endif

==========================================================

The full code is open source and under GPL2:
(https://sourceforge.net/p/testsuite240p/code/HEAD/tree/trunk/240psuite/Wii/240pSuite/source/video.c)

Let me hear what you think.

Kind regards
Yamato

**Comment by FIX94** [comment]
hey, you might want to check out the new 3.388, I found some errors in the loader code which probably affect this exact issue.

**Comment by parski** [comment]
I have this exact issue. PAL Wii connected to PVM via RGB-SCART. PAL games look fine but NTSC-J and NTSC-U are red like Nintendont. Also, I don't know if it's related to this but after a short while of playing a PAL game the colors get really messed up and don't go back to normal for a while. I think it's caused by Nintendont because nothing else is ever used when this happens. It's also sort of scary that it is persistent between reboots and that it just goes away after a while. Not very deterministic.

**Comment by carnage702** [comment]
well first you need to use version 389 and obviously you need to force ntsc games to pal 60 or else you get netsc video signal.

**Comment by Yamato-san** [comment]
@FIX94 Thanks for the update and your reply! The update made the Nintendont home screen and look correctly on my PAL Wii RGB scart cable setup. There is no red tint anymore :-)

Although NTSC region games themselves still show a red tint screen when Nintendont is set to output a NTSC signal. So the issue wasn't solved entirely by the rescent update, only regarding the home screen.

A NTSC video signal should be able to be displayed on a PAL Wii via RGB Scart cable without any problems. In example the 240p Test Suite can be set to output a NTSC video signal and it looks right. My BVM monitor accepts NTSC signals perfectly. So there is just a problem with Nintendont outputting it false via Scart connection. As you can see in Artemios code for the 240p Test Suite (please see above) there is a code which sets the Wii to output RGB via Scart cable and not YUV.

I really hope there is something you can do about it.

Thanks!

**Comment by carnage702** [comment]
thats why you go to settings and force pal60 on ntsc games wich should be almost 100% compat if your using version 389.

**Comment by Yamato-san** [comment]
@carnage702 Well that's true for the majority of games. Although the Mega Man X Collection i.e., which is one of my most favorite games, shows heavy flickering that way. There is no flickering in NTSC mode but then you have the red tint screen again.

If Nintendont could just output NTSC region games in their original video format (which is NTSC obviously) via EU Scart cable connection without any red tint then you wouldn't have to force these games into PAL60. These would be the best and most elegant solution.

**Comment by carnage702** [comment]
did you try forcing ntsc videomode on a ntsc game? still i dont think what you want to do to even be possible, and i still dont get why your not using comonent cables if your tv supports ntsc signal, the plus of using ntsc games is getting 480p not displaying them trough rgb cable lol.

**Comment by Yamato-san** [comment]
@carnage702 A Sony BVM is a CRT monitor made for 240p/288p and 480i/576i content. PAL GameCube games didn't support progressive scan. That's why I have my Wii connected to my BVM monitor so I can play GameCube games on a classical tube, which looks great in my opinion. It's great with the MMX Collection too obviously, because those games are displayed in 240p.

I have the Wii connected to a RGB Scart switch together with other classical consoles which all output RGB like PC Engine Duo, Super Nintendo and so on. That's why I am using Scart cables in my setup. You're right, it's possible to connect the Wii via YUV cables to a BVM but this wouldn't be as convenient for as just using one switch for everything.

No, it should absolutely be possible to output NTSC video signals via Scart cables without any red tint. Artemio achieved the same thing with the 240p Test Suite as stated above. I did the PAL testing for him. I think we can agree that the red tint issue is simply a bug when using Scart cables together with NTSC games.

**Comment by GerbilSoft** [comment]
The main reason why a "red" screen appears when using RGB cables on NTSC games is because the pins for RGB and S-Video (and YPbPr) are shared.

http://gamesx.com/wiki/doku.php?id=av:wii_multi_av_pinout

When running a PAL game, pin 7 = R, pin 9 = G, pin 11 = B.
When running an NTSC game, pin 7 = Y (monochrome), pin 9 = chroma, pin 11 = unused.
If component (YPbPr) cables are connected, the above does not apply; instead, pin 7 = Y (monochrome), pin 9 = Pb, pin 11 = Pr.

This is controlled by the video format value, as seen in libogc: https://github.com/devkitPro/libogc/blob/d7b03d41db96558917ea4fa212727d8f65f1341e/gc/ogc/video_types.h

Four formats (not including debug modes) are available: NTSC, PAL, EuRGB60, and MPAL. EuRGB60 and NTSC have the exact same timings; the only difference is the color encoding for composite video, and the fact that NTSC modes enable S-Video on pins 7/9 instead of RGB on 7/9/11.

Hence, the only way to get RGB on NTSC games is to patch the video mode to use EuRGB60 (or use YPbPr instead).

**Comment by parski** [comment]
Could you clarify the patching part? Is it patching the NTSC-U/J ISO or patching Nintendont to use EuRGB60? My feeling is that you mean the former and in that case, is EuRGB60 the same format as PAL60? I guess I'm asking if Yamato-san will have the same issues with Mega Man when patched to EuRGB60 as he is having with PAL60 or if the issue will be solved if a Force EuRGB60 mode is added.

**Comment by GerbilSoft** [comment]
It would be patching the game to use EuRGB60, which is basically what Nintendont's video mode option does.

PAL60 is the same thing as EuRGB60. I assume Nintendo called it "EuRGB" because it's only used in European countries that use RGB SCART. (Japan has a 21-pin RGB connector that's physically the same as SCART, but has a different pinout; Nintendo doesn't support this on Wii or GameCube.)
