### ISSUE TITLE
Black bars

### ISSUE THREAD

**Issue by MightyPrinny** [FIX94/Nintendont#236]
If the the gamecube is 640x480 why are those black bars on the screen?, i know that the screen width can be changed on the menú but it never match the screen because the number increases in pairs.

**Comment by westonlast** [comment]
I noticed this with Twilight Princess.  I assume the raw, unscaled (thank you for this feature) framebuffer that the game chooses is being displayed by default, centered in the screen (which is why your number increases by twos; to maintain centering).  I had to enable Wii U 16:9 mode in the Nintendont settings, and change the horizontal resolution (scaling) to 680, if I remember the number correctly.  This is game-specific.

What I don't understand is how the Wii U does a non-integer scaling of the framebuffer.  The Wii's video device had an analogue scaler that did this.  Since the Wii U is now digital output, there must be digital scaling being done somewhere, which is unfortunate, but that's the only way to get the correct aspect ratio.

**Comment by FIX94** [comment]
actually the gamecube outputs 720x480, how it looks all depends on how things are scaled on your tv. on top of that some games automatically add black bars around it, this is done for crt tvs which typically overscan so you can just leave some outer area untouched to save some time rendering a picture. every single gamecube game does this differently and has different base widths and heights so its impossible to always get a perfectly filled base picture without any black bars. some things use REALLY crazy settings (like the pal gamecube bios) and these cant even be displayed on a wiiu because it does not emulate all settings correctly. so I cant really do anything for you here other than saying that you have to live with the picture gamecube games give you.
