### ISSUE TITLE
Pokemon Box black screen

### ISSUE THREAD

**Issue by Cameron1084** [FIX94/Nintendont#239]
Ive been trying to use Pokemon Box with my leafgreen and everything after they connect, it goes to a black screen while the music is still playing.

**Comment by carnage702** [comment]
are you using nintendont  version 389?Also you cant play leafgreen or fire red on pokemon box incase you didnt knw you can only play ruby and saphire you can deposit pokemons tough and withdraw them.

**Comment by Cameron1084** [comment]
I've been using the version you can download on the main page here. (Away from Wii/U atm so can't check version) but I'm not trying to play leafgreen on gc, im trying to deposit pokemon.

**Comment by carnage702** [comment]
then amke sure you are on a wii since gba link cable only works on the wii trough original gc ports, it doesnt work on wiis without gc ports nor does it work on wiiu with gc adapter.

all you need is have everything on auto / off except mcemu on or off  to your liking and having native set to ON, also you gba game needs to have the same language as the GC game.

**Comment by Cameron1084** [comment]
Where can i get the latest version?

**Comment by GB-CG** [comment]
Here: https://github.com/FIX94/Nintendont/blob/master/loader/loader.dol?raw=true

**Comment by carnage702** [comment]
or you can update inside nintendont itself  if your wii/wiiu has an active internet connection.

**Comment by Cameron1084** [comment]
Thank you for the update
