### ISSUE TITLE
Twilight Princess crashed

### ISSUE THREAD

**Issue by westonlast** [FIX94/Nintendont#257]
Wii U, Wii U Pro using Bluetooth.  The clawshot ("X-button") was being repeatedly mashed while using L-targeting.  Screen froze, sound stopped, then controller turned off, and then we were returned to the Homebrew Channel.  Blame it on the wife.

These cheats were enabled:

```
No Bloom Effects [Ralf]
04009650 4E800020
```
```
No Fog & Heat Haze Effects [Ralf]
0440BF1C 3F000000
```
Nintendont 3.393
Firmware 58.25.32

I'll upgrade and hope this doesn't happen again.  In other news, the Homebrew Channel randomly boots to a black screen.  Also, a few times Twilight Princess would freeze at a black screen after pressing the Home button.  In both cases, the only solution is to pull the plug (holding the power button on the Wii U does nothing).

**Comment by carnage702** [comment]
that wasnt a crash... you hitted the home button lol which returns to the homebrew channel, the home button is the exit f nintendont and depending on how you boot it it might fail.

**Comment by westonlast** [comment]
We didn't press the Home button, though.  I'll update to the latest version if there's a new feature I want or if this happens again.

To be clear about the other news, for the "Homebrew Channel randomly boots to a black screen" part, I meant starting the Homebrew Channel from the Wii menu, so that particular issue is unlikely (I hope) to be caused by Nintendont.

**Comment by carnage702** [comment]
the black screen randomly on vwii  homebrew channel is a  normal issue when hard shutdown (holding down the power button), its kinda random on how it happens but yeah it happens not only with nintendont but with every hard shutdown of the wiiu  but its easy fixable by retrying it has happened to me when trying other homebrews like not64 and so on.

Im telling you you pressed it lol, the only way for nintendont to exit to the homebrew channel is when home button is pressed, maybe you nudged it and it activated or some other controller was activated and pressed on it there is no comand that would prompt an exit in the code, you can try it for your self get ingame and press the home button and you will see the same extact exit  you experienced, maybe you didnt noticed and you clicked on it somehow by slidding the finger over it or something i cant tell how manny people miss the start button and press home button reports we had.

return to homebrew channel fails on some games that hava data protected on some parts for example on spiderman 2 it failled to return when doing some mode thing that needed a custom fix so its unknown if all parts of all games work with it.Also exiting from a fowarder doesnt work most off the time since nintendont cant return to fowarders without having full stubs.

**Comment by westonlast** [comment]
I'll summarize to make sure I understand what you're saying:

When a game is running from Nintendont, pressing the Home button to return to the loader can fail depending on what the game is doing at that moment.  Once this black screen occurs (forcing me to pull the plug on the Wii U because even holding the power button doesn't work), the next time vWii loads the Homebrew Channel from the Wii Menu, the same black screen will occur.  Pulling the plug and retrying will work at this point because whatever was corrupted is finally overwritten?

Is there any safe way to exit a game running in Nintendont?

By the way, now my wife is doubting herself about whether she tried to press Plus and instead accidentally pressed the Home button, so this is possible.  Twilight Princess is pretty tense, after all. :P (I wish the exit command was a rare button combination instead of simply Home.)

Thank you for being responsive and explaining this to me.  You're, like, the only person in the entire world who can help me with this.  I appreciate your time.

**Comment by carnage702** [comment]
well  most of the time nintendont will exit just fine so yeah you can press home button wait for it to return to homebrew channel and then just power off the wiiu normaly, only some very rare games will block the exit  on very rare ocasions so your fine just using the home button to return to the homebrew channel its basicaly 99% garanteed to work.

also the homebrew channel black screen isnt always certain sometimes even if you hard shutdown it might work just fine so yeah its very hard to predict lol but as long as you shutdown your wiiu normaly it should work fine mostly.

there isnt much to help with since its very rare ocasions.
