### ISSUE TITLE
Mario Kart GP and 2 occasional video pauses

### ISSUE THREAD

**Issue by westonlast** [FIX94/Nintendont#267]
Nintendont 4.410

Sometimes the video pauses for 300 milliseconds or so.  The sound is unaffected.  I'm using the Force Progressive setting and Cheats "yes," (because it's pain to toggle back and forth between games), but I don't have any cheats for these games.  Other than this, the games seem to work.  I assume the video shouldn't pause like this.

**Comment by carnage702** [comment]
maybe its becuase of the force settings you have or your SDusb is too slow to keep up?

are you using an SD card? did you try to take ut force progressive?

**Comment by FIX94** [comment]
that is pretty normal, if you look up how it ran back with quadforce you can be happy with how it runs now. loading it from sd can improve the situation even more but it still will be slower than the real arcade, thats because the GP games normally are loading data instantly directly off of a NAND chip and are optimized for that so introducing normal device loading is very noticable especially from HDD because of its very slow seek time.

**Comment by westonlast** [comment]
I'm using a Class 4 SD card (4 Mb/s).  Maybe a higher speed class would have better results.  Thanks.

**Comment by GerbilSoft** [comment]
Class 4 is minimum *write* speed, not read speed. Your card is likely capable of at least 10 MB/s read; the limiting factor is the Wii's SD slot, which IIRC is limited to around 2 MB/s. You may want to try a USB SD reader, since the USB ports are much faster.

**Comment by westonlast** [comment]
I got my information from here: https://en.wikipedia.org/wiki/Secure_Digital#Speed_class_rating

"The specification defines these classes in terms of performance curves that translate into the following minimum read-write performance levels on an empty card and suitability for different applications."

Wow, I assumed that SD is inherently better than USB... because it's "closer."  Thanks for the insight!  (No reason to go out and buy faster SD cards, people.)
