### ISSUE TITLE
Init card... Freeze and Reboot

### ISSUE THREAD

**Issue by Mohamed28** [FIX94/Nintendont#271]
Hi, 

I am experiencing this if i use memory card simulation!

**Comment by carnage702** [comment]
could you take a picture of your nintendont settings?

**Comment by dna5654** [comment]
okay, so because he never turned up i guess i will continue. i installed the most recent version of nintendont and tried to play a game i had but i realized i was missing my memory card. thus i enabled memory card emulation and set it to 123 blocks i believe it was. later i tested it out on every other block option and enabled the multigame card function as well. sadly, upon loading the game, each and every time, it would freeze and require a restart of the system to function again, yet it will still freeze at the same point. when i opened the sd card i had nintendont on, i saw that nintendont was creating the raw file to save the game but it would freeze while actually making it, resulting in .raw files that consisted of nothing(0kb). So as a result i tested it out on my wii U as well as my wii again but encountered the same problem. Later i took the 16 mb raw memcard  used by dolphin and renamed it ninmem to use for nintendont... it loaded up, so the only problem was when actually writing to the card. it may be an sd card specific problem, where it cant fully create a raw file but i dont know if it can still modify an already existing memcard as it froze when creating gamesaves. i was using a 16mb raw file so that could be why the dolphin card will not be compatible.

Still i do not know the root of the problem, but it may be useful to users if the various sized memcard .RAW files can be available for download in the case that their wii cant create them as mine does

**Comment by carnage702** [comment]
you sure your sd card isnt locked? also are both your isos and nintentendont app are all on SD?

the recomended setting is maling nintendont have 251 blocks and multi off that way it creates a single memory card for each game wich is much safer than having a multi memory card where if one save corruts it will kill all your saves.

**Comment by dna5654** [comment]
My sd card wasn't locked and i would use a smaller sized virtual card if it
would create one at all

**Comment by carnage702** [comment]
do you have both nintendont isos on sd and app? or is a mix of sd and usb?

**Comment by carnage702** [comment]
Also like i said the first poster take a picture of your nintendnt settings.

**Comment by dna5654** [comment]
Only sd

**Comment by carnage702** [comment]
take a picture of your nintendont setiings. also are your games good dumps? full 1.35 gb isos with md5 checked on redump?

**Comment by dna5654** [comment]
I have to rest a bit now so it isnt a good time for this but i will take
pictures of what im seeing tommorow

**Comment by GB-CG** [comment]
@Mohamed28 @dna5654 Try delete the Homebrew channel save data (1 Block) in the Wii save data Management settings and then try again. It's only a cache file and it may be corrupted?

**Comment by dna5654** [comment]
Oh sorry i guess i didnt post back. The problem is purely hardware based.
My sd card was not efficient enough to write files as fast as it should
have. Its kind of hard to explain but i just went and got a new one and the
problem was no more
