### ISSUE TITLE
FST / Extracted support?

### ISSUE THREAD

**Issue by ppsspp213** [FIX94/Nintendont#280]
What's the story, no one wants to talk about it like it's a dirty word.
Is it because said extractors don't extract the files properly creating corrupt / incomplete files or another issue? can we get a definitive reason as to why?
I've noticed that some of tools the won't list or extract the &&systemdata folder properly if the gcm has been shrunk or had the padded data removed.

Known tools that extract gamecube gcms being and probably more that i've missed.

VGMToolbox
DMToolbox
GC-Tool
Dolphin
GCRebuilder
GCReEx 
GCIT 
wit

**Comment by carnage702** [comment]
the story is that is much slower to load the files you will have much longer loading times and most gc games arent moded so theres little point in increasing the load times but fst is supported so what do you exactly want?

**Comment by ppsspp213** [comment]
^ How to setup / place the folders with it and which tool to use.
There literally no documentation on how to use it in gbatemp thread.
Also why is it slower when it's not reading any dummy data?

Same goes for not recommending shrinking gcms, whilst a few of the shrinkers caused problems, i've yet to find any with dsbomb gcm tool 
https://www.blogger.com/comment.g?blogID=6135395526335999018&postID=8115829955564790110&bpli=1

**Comment by FIX94** [comment]
nintendont emulates the disc drive so all we get is a offset to read and which size the game wants from it. for a iso file that just means, seek to that offset and read it. on top of that iso files have their entire layout on your device cached so it doesnt even have to read out any FAT and can just go to the place directly making it the fastest thing possible. fst on the other hand is pretty crappy, you have to interpret whatever offset you get to somehow get a pointer back to the file that means, then you have to seek through the whole directory tree (a lot of FAT reads, very slow!), open the file (gets file size and its position on your device, very slow!) and then seek around in the file and read what the game wants finally closing the file again. overall depending on the game you dont even get 10% of the performance you can get with a iso file, thats why I really dont talk about fst, its technically there but thats about it. now for actually using the thing (didnt do that in years) you place the root and sys folder or whatever you get again into a new folder in your games folder. oh yea there also is the limitation of fst that disc swapping is not a thing so 2 disc games or whatever arent usable as nicely with it. oh and for why I do not recommend shrinking its as simple as getting less error reports with it, you can check your iso hash if its a valid rip and just gets a whole layer of possible user or program error out of the way, games like kirby air ride by the way are known for being very weird with shrinking. oh and shrinking literally gives no speed advantage, neither from sd/usb (because the location is cached) nor from dvd (the later offsets on a dvd read out faster).

**Comment by ppsspp213** [comment]
Ok thanks for explaining it, so it's better to rebuild an iso for mods?, I was just looking for an easier method like riivolution.
Game consoles use lba table / filesize for reading disc files rather than filenames with dictionaries
how is windows then say able to read files so quickly, doesn't it use a index or jet? couldn't we reuse 
that?, you already mentioned fat, couldn't we just locate first file of the extracted disc and assume the rest of the files lead off that / come next for that game dictionary on the hdd? so it isn't constantly seeking the files?

**Comment by GerbilSoft** [comment]
On GameCube, games read the disc directly, and all licensed titles assume that the disc uses Nintendo's FST format for the file system table. Hence, Nintendont has to create a "virtual" FST that looks like an original FST to the game, and then it has to keep track of where virtual sectors map to actual files on the HDD. That's part of the reason why extracted FST is so slow. We also can't assume that files on the HDD match the order they were in on the original disc, since 99% of the time they aren't.

On a PC operating system, programs don't access the storage device directly; they use syscalls to request file data from the operating system. The OS then handles the details about the low-level file system, which usually includes lots of caching.

**Comment by ppsspp213** [comment]
^ I thought game discs followed the 8.3 standard? with the smallest file appearing first and biggest last so the read speed is optimized to the laser position with the disc at it's widest point for least revolutions.

**Comment by GerbilSoft** [comment]
GameCube FST allows arbitrary-length filenames. (8.3 is an MS-DOS FAT limitation; not applicable to GameCube discs.) The positioning of files on the disc is entirely dependent on the developer; some may optimize games properly, while others might not.

In any case, that still has no effect on how the files are laid out on an HDD or SD card if you use extracted FST. Your OS may decide to organize files differently even if you extract them in FST order, or the FST order might actually not reflect the order on disc.
