### ISSUE TITLE
Marjora's Mask, Ocarina of time skip bios boot / wrong video mode.

### ISSUE THREAD

**Issue by ppsspp213** [FIX94/Nintendont#284]
I'm running the converted tgcs from PZLE-USA but both of them have the game id 
RELS01 which seems to the reasoning behind it booting both games in 576i, the S part being recognized as Spanish for PAL, forcing 480i/p and PAL60 causes it to black screen.
It also skips the bios booting for both games.
If i'm running these games extracted do I need to edit the game id from RELS to PZLE so it can set the game as NTSC matching the actual disc and apply the correct patching? or will using their n64 ids suffice?
NZSE
CZLE
Also both converted tgcs have no gamecube banner.

**Comment by FIX94** [comment]
why do you even convert them and not just run the actual collectors disc, any reason? and yes you would have to change its game id, now as long as it ends on "E" it will use ntsc, the other part of the id really just is its save name on the memory card. the game id RELS and no gamecube banner just means they never intended you to run these as standalone because these are their placeholder/default settings when building a gamecube image.

**Comment by ppsspp213** [comment]
Today I tried to launch both n64 games from the full disc, but I still get a black screen as if it's switching to some unsupported video mode on my tv.
The zelda game selection screen displays in both 480i/p fine as does the windwaker demo.
The Nes games display in 240p.
I'm using a PAL Wii RVL-001 with component cable.

**Comment by carnage702** [comment]
make sure your not using width since those blackscreen n64 games

**Comment by ppsspp213** [comment]
^ thx that fixed everything.
