### ISSUE TITLE
Memory Card Virtual corrupting

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#288]
Quando uso o Nintendont ultima versão junto do Wiiflow os jogos GC carregam sem o Memori Card Virtual mesmo habilitando toda vez que recarrega o Nintendont ele fica desabilitado de inicio.

When I use the latest version with the Nintendont Wiiflow GC games load without Memori Card Virtual even enabling every time recharges Nintendont he is disabled to start.

**Comment by carnage702** [comment]
well loaders have their own nintendont settings, so maybe outdated wiiflow im guessing? If you use nintendont directly from the homebrew channel and this doesnt happen then its not a nintendont issue but  wiiflow issue therefore you need to report it to wiflow not here since nintendont isnt the issue.
