### ISSUE TITLE
DSI Exception

### ISSUE THREAD

**Issue by aznlilchino103** [FIX94/Nintendont#289]
Works fine:
- Nintendont v4.416
- Build: Jul 9 2016 18:27:33
- Firmware 58.24.32

Broken (Exception (DSI):
- Nintendont v4.416
- Build: Jul 16 2016 00:32:45
- Firmware 58.24.32

**Comment by carnage702** [comment]
did yiu tryed version 419 the latest released? also make sure to delete cntroller.ini and ninconfig.bin on the root of your usb/sd sometimes they go corrupt and break nintendont

Also how can 416 be both broken and working?

**Comment by DankRank** [comment]
@aznlilchino103 
I assume that you meant that 419 is the broken one, since it's the one with the build date of "Jul 16 2016 00:32:45".
I checked 416, 417, 418 and 419 and they all run fine on my Wii.

Please provide more details so we could figure this out:
- Does it crash on all games or only on certain ones? (if so, which games does it crash on)
- What options do you have enabled?
- Try running 417 and 418 and see if you're still getting the exception.
- Are you using any kind of loader (like USBLoaderGX), or are you using nintendont directly?
- Do you have Wii or Wii U?

Here are links to the recent builds, if you need them: [416](https://raw.githubusercontent.com/FIX94/Nintendont/77fe0c/loader/loader.dol) [417](https://raw.githubusercontent.com/FIX94/Nintendont/c8df26/loader/loader.dol) [418](https://raw.githubusercontent.com/FIX94/Nintendont/27595e/loader/loader.dol) [419](https://raw.githubusercontent.com/FIX94/Nintendont/ea4b9f/loader/loader.dol)

**Comment by aznlilchino103** [comment]
- Does it crash on all games or only on certain ones? (if so, which games does it crash on)
   -> Crashes during startup (Checking Devices)
- What options do you have enabled?
   -> Only Native Controller (I have a Wii with GC ports)
- Try running 417 and 418 and see if you're still getting the exception.
   -> Will reply in a later post and try it out.
- Are you using any kind of loader (like USBLoaderGX), or are you using nintendont directly?
   -> Tried both and it gave me the same error.  However, I haven't tried deleting the ninconfig.bin (still need to look for controller.ini)
- Do you have Wii or Wii U?
   -> Wii with Boot2 Capability (Older one)

**Comment by aznlilchino103** [comment]
Sorry been busy with life events but here's an update:
So went back to "416" and updated to "422" using the interface.  Noticed that it also updated the XML Meta file.   Tried two games and it launched fine thru Nintendont directly.

My guess... corrupted XML Meta file?
