### ISSUE TITLE
Nintendont not working on External HDD

### ISSUE THREAD

**Issue by patricksouza472** [FIX94/Nintendont#291]
I'm having a hard time making my WD My Passport 1TB USB 3.0 external HDD (Product ID 0748, FW revision 1022) to work with this (also, Homebrew Channel detects it but also won't see the apps contained in the HDD). Nintendont just doesn't detect the games folder, others apps like MPlayer CE, USB Loader GX and WiiXplorer work perfectly. USB 2.0 thumbsticks work just fine, SD card also working.

**Comment by carnage702** [comment]
is it formated to fat32?

**Comment by patricksouza472** [comment]
Fat32 32k cluster size. Same thing happens to my friend's Samsung 320GB external HDD. Wii console on both cases

**Comment by carnage702** [comment]
wii or wiiu? if you can take a picture of your hdd setup from the root to inside the games folder to inside a game itself seeing the iso.

**Comment by patricksouza472** [comment]
Yes, entirely fat32, primary, active, MBR partition table. Can't post pics right now but here's an example path: USB:/games/fzero/game.iso
Even tried copying the entire games folder from my 32GB SanDisk Ultra SD card which is working perfectly. Didn't work

**Comment by carnage702** [comment]
are you using the latest nintendont?  right now version 419? do you have more than one usb device connected to the wii? if it doesnt detect your games folder something it soof, its either reading a partition that doesnt have them or straight up cant read your hdd.

**Comment by OTFree** [comment]
May or may not help, but try including the individual game ID's in the
folder names where you put the isos.

For example, if you used fzero, the path would look like this:

USB:/games/fzero[GFZJ01]/game.iso

**Comment by carnage702** [comment]
that only matters if he tries using nintendont trough usbloadergx or some loader, nintendont doesnt care about the name of the folder since it actualy reads the iso and then puts the correct game name.

**Comment by patricksouza472** [comment]
Latest version, only one USB drive connected. I think it does recognize the HDD as it gives me a different error if I unplug it. Just doesn't see the games folder. Could it be IOS-related staff? Also, I'm willing to back it up and reformat it if needed

**Comment by carnage702** [comment]
No idea maybe a full format without any partition being pure fat32 would help.

**Comment by Brothers2000** [comment]
No se por que en las ultimas versiones de nintendont si el HDD esta particionado para que funcione tienes que cambiar la particion de los juegos a LOGICA, si esta en primaria no funciona.
El problema es que al querer usar nintendont con UsbLoaderGX no se puede por que te pide que los juegos esten en  una particion primaria y al cambiar la particion a primaria te muestra error.
Bueno eso es lo que yo hice y me funciono.

I do not know that in the latest versions of nintendont if the HDD is partitioned to work you have to change the partition of games as LOGICA, if this primary does not work.
The problem is that when using nintendont with UsbLoaderGX not work because the games are in a primary partition and change the partition to primary nintendont not work.
I had the same problem and it worked.
