### ISSUE TITLE
ABH Access Error: Nintendont in USB Loader GX

### ISSUE THREAD

**Issue by KingCornWallis** [FIX94/Nintendont#298]
Simply does not work. Latest Versions of both...Paths and settings adjusted...Nintendont works fine by itself, will not work in USBLGX.

**Comment by GerbilSoft** [comment]
Does USB Loader GX's meta.xml have <ahb_access/>? (Or <no_ios_reload/> for older HBC.)

**Comment by thericeking** [comment]
I signed up to GitHub just so I could comment on this issue. I can confirm that I am also having the exact same issue since I updated to the latest Nintendont. I didn't have this issue with USB Loader GX before. Thank you so much for your work. Nintendont is my favorite Wiibrew app (Homebrew).

**Comment by Nube2021** [comment]
Hey, same issue here, it doesn't work with USB Loader GX and I have definitely a <ahb_access/> in my meta.xml.

However, there is also an other issue. When I use Nintendont on USB Port 0, every game crashes after some minutes ("An error occurred..."). When I switch to USB Port 1, everything seems fine.

**Comment by carnage702** [comment]
that seems to be your wii issue lol im guessing your wii usb port is dying, we had someone here that every game for him crahsed after 10 mins or so and he tryed dios mios too and same issue, the wii material isnt very sturdy even it has been reported even during the wii active times that some people usb ports got damaged and stoped reading devices or straight up crashed once readed from there and such.

**Comment by Nube2021** [comment]
@carnage702 This explanation doesn't sound logical to me as port 0 (which crashes every 10 minutes  when using Nintendont over HBC) works perfectly with USB Loader GX. For me this is the lesser problem compared to the one that Nintendont can't be started through USB Loader GX. If it would work with USB Loader GX, the issue with the port would be solved as it exists only when using Nintendont through HBC.

By the way, from the first day I used this Nintendont version, I had a third issue that somebody else here also posted. This also happens when using Nintendont through HBC. When I press the home button (whether on my Wii Mote or on Classic Controller Pro) while I am in the main Nintendont menu (in order to get back to the HBC menu) it shows me a black screen with some error codes and at the bottom of the screen it says that it will reload in 10 seconds. But it freezes there so that I have to restart my Wii with the power button. This only happens when I press the home button from the Nintendont main menu. When I press button while playing a game, everything works fine and I get back to the HBC menu (by the way, wouldn't it be more user-friendly to first get back to the Nintendont menu?).

**Comment by carnage702** [comment]
nintendont freezes when exiting most fowarders that is normal due to not having enough information to return, also if you somehow have an old homebrew channel or installed a custom color/theme it can cause issues with nintendont.

usbloader gx on wii games is much diference than nintendont  using usb for gc games its all very diferently coded and even the processor it runs on and the ios and so on, nintendont uses usb much more agressively than any wii usbloader using usb for wii games.
