### ISSUE TITLE
can i Play with 4 wiimotes only?

### ISSUE THREAD

**Issue by darkto62** [FIX94/Nintendont#300]
Hi, there is a way for play with 4 wiimotes only?
without nunchuck.

**Comment by carnage702** [comment]
no solo wiimotes are nor supported at all not even for one person, if you dont have nunchucks or CC to connect to those wiimotes then you cant do 4 players.

if you have hid controllers or gc controllers or even a wiiu pro you can do a mix like 2 players using wiimote+nunchuc another using a wiiu pro and another using an hid controller  you can mix them, but yeah solo wiimote is not supported and it will never be due to the extreme lack of buttons for  over 90% of the games.
