### ISSUE TITLE
Metal Gear Solid: The Twin Snakes USA disc 2

### ISSUE THREAD

**Issue by Oxinar** [FIX94/Nintendont#301]
The game hangs as soon as the fight starts with Vulcan Raven in the warehouse if you are using cheats. 
Have Nintendont version 4.21

**Comment by carnage702** [comment]
nintendont doesnt share all the gc memory adresses due to being in wii mode, so its to be expected some cheats can break some games the only way to do fix that would be someone decoding the cheat and then porting it to nintendont mode wich i doubt any hacker would take his sweet time to do so yeah unless you know how to do it you will have a very hard time to find a game hacker that wants to loose time fixing this.
