### ISSUE TITLE
Sonic Heroes Widescreen has gone weird.

### ISSUE THREAD

**Issue by Maesejesus** [FIX94/Nintendont#303]
Hi, I wanted to inform that I just noticed that Sonic Heroes (NTSC-US version if it helps) appears with some minor problems when using Force Widescreen.

I tried with an old version of Nintendont just to be sure it wasn't my memory (Verison 3373) and yes, the newer ones (I tried with 4419 and 4422) had several minor visual problems:

Everything seems to be normal on the menu, but once you get into actual gameplay, the font graphics for things like score, ammount of rings, time and lifes appears tiny and it overlaps in several places. The dialogue between characters shows on the lower-left part of the screen instead of the center, it also has a smaller font (And the text is crunched together too. It can be read, though). The text for the final of a level also overlaps itself.

If it's of any help I could make screenshots with the "right" widescreen and the wrong one.

**Comment by carnage702** [comment]
Someone i think gerbilsoft ported the sonic heroes patch from dolphin to nintendont what you are seeing now is actual widescreen before the widescreen hack didnt worked it did absolutely nothing to the game all you got was just sctretched 4:3, so yeah obviously since widescreen hacks basicaly are just hacks they have issues and such so yeah if you want to complain, complain to the dolphin guy that made that sonic heroes patch for widescreen nintendont just ported it so it actualy did something instead of you getting stretched 4:3 like before, if you dont like it just turn force widesccreen to off and you will still get a full scnreen stretched picture like before on wiiu you still need to force wiiu widescreen tough to get stretched view like before on wii its like that by default.
