### ISSUE TITLE
Thanks ! really this is an amazing work!

### ISSUE THREAD

**Issue by darkto62** [FIX94/Nintendont#306]
we still Need PSX emulator and Nintendo 64 for the wii for make it the best console with emulators!

Wii never dead! thanks to this amazing work!
really, thanks! ;)

**Comment by GB-CG** [comment]
Sorry, but it's not an emulator.

**Comment by carnage702** [comment]
preety much what he said, nintendont is not a full emulator, it doesnt emulate the most important parts like graphics processor and the CPU since they are inside the wii/vwii itself so no need to emulate them, nintendont does emulate some parts of the gc that arent there but yes its mostly  a mix of emulation and native.
