### ISSUE TITLE
Issues with Nintendont on SD card and games on USB

### ISSUE THREAD

**Issue by xombiemp** [FIX94/Nintendont#311]
I was running into some problems with Nintendont when it was installed on my SD card and my games were on a USB drive.
I'm running vWii on Wii U and my usb drive is Ustealth'd.  I tried to launch a game from USBLoader GX and I kept getting an error that the save file could not be created.
Also when trying to update Nintendont from it's own interface I kept getting Update Error: -3.

I then moved Nintendont to the USB drive apps folder and all the problems I was having went away.

It seems like having Nintendont on the SD card and games on the USB should be a working configuration.

**Comment by carnage702** [comment]
being u stealth could also cause an issue since i have no idea what usb code is used for each connection and might not detect a drive if its hidden and whatnot, but yes it has been reported that nintendont sometimes gets confused when its runned from the SD and the games are on the usb, but this is only an issue for some people i guess due to their setup or something.

**Comment by xombiemp** [comment]
Sorry! I was mistaken about being Ustealth.  My main machine is Wii U, but in this case I was modding a friend's original Wii.  So this occurred on a regular Wii with a non-Ustealth drive.
