### ISSUE TITLE
Snes Style - Wireless Bluetooth Game Controller for Wii U - not working

### ISSUE THREAD

**Issue by fabiotc** [FIX94/Nintendont#314]
Hi guys,

I know there are some problem with generic Wii U Pro Controller, but in this case (Wireless Bluetooth Game Controller for Wii U). Is there any workaround to work?

I'm using the last version of Nintendont, and with original Wii U Pro Controller is working, but not with this "generic" version..

Thanks

**Comment by GerbilSoft** [comment]
Nintendont has issues with many third-party Bluetooth controllers, mostly because of slight deviations from the original protocol.

Can you get the BT vendor and device number? On Linux they're accessible using 'hcitool scan'; on Windows, they might be listed in Device Manager under Hardware IDs. (VEN and DEV or something like that.)

**Comment by fabiotc** [comment]
Thanks @GerbilSoft 

I'll get those informations later today.

And just to let you know, this is the controller I'm talking about:
http://i68.tinypic.com/2nakv1l.jpg

**Comment by carnage702** [comment]
Also never say you are using "latest nintendont", how manny times did people said this and they were 30+ revs behind or more so when you can say the actual version number you see on the top left corner of nintendont.

**Comment by fabiotc** [comment]
Ok @carnage702 

I'm with commit "1ac0fdf55fae3f21cc7c49c5b9fb42fb55235958" (master branch) version  =)

Actually I've downloaded the loader yesterday


Thanks

**Comment by fabiotc** [comment]
Hi @GerbilSoft 

# sudo hcitool scan
Scanning ...
	88:C9:D0:2C:10:62	LG-A395

**Comment by GerbilSoft** [comment]
Checking the Nintendont code, it connects to Pro controllers based on the device name, which is correct here (ends in "-UC"). There were some changes a while back that were supposed to help with "fake" Pro controllers, but I guess this one is doing something unusual.

**Comment by carnage702** [comment]
it probably sends alot of wierd signals when connecting, the changes fixed most fake wiiupros.

also isnt that controller a **Pro controller** and **not a wiiu pro controller**?

https://www.amazon.com/Pro-Controller-Wii-Nintendo-U-6304900/dp/B009O3WU2A

this means its basicaly a CC and not a wiiu pro controller, and fake cc and fake wiimotes codes are much harders since this pro controller mimics a wiimote with an attached pro controller, so who knows what wierd code it uses.

**Comment by fabiotc** [comment]
Hi @carnage702 

Actually this is the right one:
http://www.gearbest.com/game-controllers/pp_358521.html

And It's only compatible with Wii U, not Wii.
