### ISSUE TITLE
Sugestion: Port to Wiiu

### ISSUE THREAD

**Issue by marceloMedeiros** [FIX94/Nintendont#327]
Is there any plans to port nintendont to run natively on wiiu? (now that we have acess to Iosu)

I know i can already run Nintendont on vWii, but being able on Wiiu mode would open a plethora of new possibilities/improvements:

1 - Use of the wiiu gamped as a controller
2 - Being able to load games from usb even when a wiiu harddrive is connected to the USB
3 - Support for the extra 2 USBs, so you can use an USB controller even when the 2 back usb ports have USB storage devices connected.
3 - Convenience of running it without having to boot to vWii 
4 - And so forth.

**Comment by Zetchzie** [comment]
I doubt they will do this even though its a great idea

**Comment by carnage702** [comment]
1- this could be somehow achieved  if someone cracks the cafee2wii program and allows gamepad to work in vwii mode like the wii  games work on wiiu shop channel.

2-NO- nintendont usb stacks is only fat32 compatible, the wiiu mode hdd doesnt even have any sort of known fat system, hell how would you even open your wiiu hdd on the pc to add gc games? and a wierd usb stack would need to be created from scratch to read a wiiu formated hdd.Also if you were implying having 2 hdds on at the same time it would still crash since nintendont would try to mount the wiiu hdd all the same and crash.

3- on wiiu VWII you can already use all 4 usb ports lol, i do this all the time, nintendont supports all 4 on vwii.

Second 3 i guess- Someone had a sugestion of making in the future a nintendont icon on wiiu home menu that would start nintendont directly on vwii like the e shop channel games from WII that run on vwii and you never need to press vwii per say.

The problem of porting to nintendont is nintendont is not an emulator, it runs mostly native code with some components emulated that arent in wii mode, nintendont doesnt emulate graphics since the wii and GC have the same graphic processor GX, on wiiu mode there is no acess to GX only GX2 and nintendont would need to start emulating graphics and so forth wich would cause all sort of issues since emulating GC graphics is a pain.

**Comment by fadetonoir** [comment]
2 - This might be possible if you could partition your external USB hard drive, format the second partition as FAT32 and put all your Wii/GC games on there and then hide it with uStealth (which you might already be using to stop Wii U mode from prompting you to format your vWii HD) but allow Wii U mode to detect and format the first partition for itself. Not sure if that would work - maybe not if Nintendont has problems when a Wii U formatted HD is connected - but perhaps there will be a more elegant solution as IOSU hacking progresses.
