### ISSUE TITLE
Restart button combo is an issue in SSX Tricky 

### ISSUE THREAD

**Issue by mrneo240** [FIX94/Nintendont#328]
The default down+B+Rtrigger+Z combo is resetting nintendont while trying to backflip tricky move in this game for me. Sadly causing frustration with myself and friends. Where is that combo located in the source? Id be happy to change it in my own branch. I quickly looked through the source but was unable to easily find where this is located. What source file is this in? I can take care of compiling this on my own. Thank you got creating this software

**Comment by carnage702** [comment]
are you using nintendont on a real wii with gc ports? if so you can enable native and disable the reset combo.

**Comment by mrneo240** [comment]
Yes. Real Wii hardware with 4 wired GameCube controllers. Is native in
settings?

**Comment by carnage702** [comment]
yes it is, with native on you will loose the ability to exit nintendont, use  usb controllers or bt controllers, but gc controllers will work like native, as well as gba link cable and other peripherals.

**Comment by mrneo240** [comment]
Great! That's fine for me. Mark this closed, I had no idea what the native
setting did

**Comment by rootyElf** [comment]
This issue is not completely resolved tough. Native Controls is only useful, if you use an actual gamecube controller. If you use Bluetooth or USB (which are the only options on Wii U) there is still no workaround which makes SSX Tricky unplayable.

If some one wants to change the combo in source:
You need to edit the file loader/source/ppc/PADReadGC.c. On line 198 and line 1244 (might change in the future) you need to change the number 234 (the shutdown combo) to another one.
You can use this website to find the code you need: [http://www.geckocodes.org/index.php?arsenal=2](url)
I changed the combo to L + Z + Start (1050). This means both lines are 
`		if((Pad[chan].button&0x1050) == 0x1050)`

**Comment by jct123junk** [comment]
Can you please explain how to do this? I can find the .c file as well as the lines that need changing, but I'm not sure what to do with that. I am new to programming and would appreciate any assistance! Thanks.

**Comment by rootyElf** [comment]
To compile nintendont you obviously need you obviously need devkitPPC. I'm afraid you will have to find your own way to set you build environment up. I can't give you a step by step guide, because this depends on your system. You can download a build I made [here.](https://www.dropbox.com/s/6qg6rxf69f9dz3t/nintendont.zip?dl=1) It has got the change I mentioned above. This of course comes without any warranty.

**Comment by jct123junk** [comment]
Thank you for sharing rooty. I noticed that the default reset combo of LRZS no longer works. Not a big deal since I rarely use the reset function, but did you happen to change the reset combo as well? Or is the new LZS quit combo just overriding it?

**Comment by rootyElf** [comment]
The default reset combo is RZS. For me this works. The shutdown combo does not seem to work, though. I updated the build, it should be working now.

I am not sure, if this was my fault, though. I tried building it without modifications and the default shutdown combo did not seem to work there either. In my new build i made an additional if statement which seems to make it work again.

**Comment by jct123junk** [comment]
Your build is working great for me, LZS for quit and RZS for reset. No issues, thank you again!
