### ISSUE TITLE
Issue loading games in Nintendont 

### ISSUE THREAD

**Issue by KumquatKiller** [FIX94/Nintendont#376]
So I finally got around to getting nintendont on my wiiU. After a couple of attempts at getting it to work, I've stumbled upon an issue I can't fix. I can go through the loader and be able to select a game file. 
![image](https://cloud.githubusercontent.com/assets/26215024/23599038/764db116-020c-11e7-8565-3d1aa7cf5f7b.jpg)
But after I select a game file the game does not run, it either incounters a black screen or the Nintendo logo
![image](https://cloud.githubusercontent.com/assets/26215024/23598960/f7e7fcb4-020b-11e7-8ef9-712b0a5afd29.jpg)
 when running Pokémon Coliseum. If you have any tips on why this is happening they would be appreciated.

**Comment by carnage702** [comment]
are you using sd or usb? also all your isos are shrunken, you should use 1.35 gb iso wich matches redump md5 to get better compat.

**Comment by KumquatKiller** [comment]
I'm using a USB, and I'll have to check the iso's and get back to this

**Comment by carnage702** [comment]
y cable or has its own powe suply?

**Comment by saiaa64** [comment]
Hi , I had the same problem but I fixed it .
All you have to do is redownload the files but DONT EXTRACT THEM TO YOUR SD/USB  you'll need a 1:1 full dump which you can recognize by checking the file's size since 1:1 full dumps allways have a size that is about 1,35 gb big . I hope this was helping you and enjoy your time playing on Nintendont ( btw I found this out by pressing 1 on the game ) .
