### ISSUE TITLE
Add Read-Only NTFS Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FIX94/Nintendont#38]
```
I use my HDD for more than GC/Wii Games, and I don't want to be partitioning it 
- can we please add support for NTFS?
```

Original issue reported on code.google.com by `PFCKruto...@gmail.com` on 11 Jul 2014 at 11:56

**Comment by greysondn** [comment]
Can I ask - why was this closed? Is this a "won't-fix" or has it been implemented or some other third thing..?

**Comment by carnage702** [comment]
Fix94 and the other devs already said they have no intention to add  ntfs support, everyone that is into wii homebrew needs fat32 regardless since 99% of all homebrew is fat32 only its not even worth the time to code such a complicated thing becuase no GC iso is even over 1.35GB so there is no reason to use a ntfs drive at all to much trouble to code for absolutely no reward.

**Comment by greysondn** [comment]
> no GC iso is even over 1.35GB so there is no reason to use a ntfs drive at all to much trouble to code for absolutely no reward

Um, how about "I have one external drive and it's got files on it well over that size because I work in multimedia"? Or even just, you know, that's the type such a drive is and I'm unable to move everything off it to format it, at the very least?

I know that many people have dedicated drives for their "backups" but it's not always the case for everyone. To think that a drive wouldn't need to be NTFS because "reasons" is like asking why any system of any type ever had to exist.

So it's a won't-fix. Okay. I'll look forward to kludging support in, then.

**Comment by carnage702** [comment]
You dont need 2 drives you can just make a fat32 partition and be good using the same drive so yeah still no use.

**Comment by greysondn** [comment]
In-place partitioning is messy at best, even using `parted`. You're not "solving the problem by making helpful suggestions" nearly as much as you're "making excuses" at this point. Arguing with me is a waste of time; in my circumstances I don't really get a lot of a choice. In the circumstances of others, it's really just asinine to think that you can cover every single use case and need.

At this point, It wouldn't be unheard of for me to implement very poor NTFS support in a public fork just to give you headaches for acting like this. "Upstream won't-fix" was quite sufficient. I don't need you to try to convince me. I needed you to answer a simple question because the answer wasn't immediately evident when I searched NTFS in the tracker.

I'm honestly laughing you're being so ridiculous by this point.

**Comment by carnage702** [comment]
Im the one laughing  you didnt get the point at all.

The point is the nintendont dev team wont code ntfs because they deemed it unecessary long time ago, of course anyone is free to fork nintendont and do its own code that is why its an open project.

**Comment by greysondn** [comment]
So, let's get this straight - you're not a dev. You're just some guy who is probably a user and by extension has no respect at all for developers.

We're done here. We'd have been done sooner if I would have realized you could be dismissed.

**Comment by FIX94** [comment]
hey hes my main tester for the program so dont you come up with that. The whole project is open source so YOU can go ahead at any time and add it in by the way, I sure wont.

**Comment by greysondn** [comment]
This entire conversation could have ended with a four word reply immediately after my question.

"This is marked wont-fix".

You're quite welcome to have any help you care to, and I know at times it's "whoever you can get that at least somewhat able to be trusted", but you need to pick people who don't go out of their way to convince people when simple questions are asked.

**Comment by carnage702** [comment]
So becuase i offered you valid ways to use your drive with nintendont im not a thrustworthy person? Seriously your talking like i tryed to convince you into doing drugs or something, its normal for people when they ask a question, wanting to know all the possibilities and that is what i gave you, i clearly said nintendont team said they wont code ntfs becuase they found it unecessary and i gave you the choices of you codding, ntfs support yourself, formating your drive fully to fat32 or do a simple fat32  partition on the drive and keep the ntfs side, just read abode the first post i clearly said nintendont team found it unecessary to code becuase all homebrew is fat32 preety much and gamecube isos dont require it either this was just the explanation why they found it unecessary.

**Comment by greysondn** [comment]
> im not a thrustworthy person? 

I'll thank you in the future to not put words in my mouth.

> All the rest

Do you think that repeating yourself will change my mind? Move on with life. Quit wasting what precious little time you get on this planet wasting my time.

**Comment by Squall-Leonhart** [comment]
Fix94, he might be your main tester, but he is completely obtuse and presents his own opinion as facts and reasons for dismissing valid suggestions, he also likes to waffle on to detract from the topic at hand.

He is not someone who any end user should have to put up with getting a Yes/No from.

NTFS support is required,  the fact that other homebrew don't have it is a non issue, these would simply be loaded from an SD card and are most often not even a fraction of the size of a GC game.

**Comment by hito16** [comment]
I'm super new to Nintendont and I too am interested in NTFS support.  Its been very confusing looking over the Nintendont NTFS threads on the different sites due to all the hear-say and misinformation.   This seems like the closest thing to an active thread on NTFS, so for posterity, here's what I've been able to confirm through some direct research and experimentation.

Misinformation 1: (no shocker)  There NTFS support in the Nintendont source code  I've confirmed what is needed and the Nintendont code .  This thread is WRONG http://www.theisozone.com/forum/viewtopic.php?f=59&t=51048  

Misinformation 2: Adding NTFS support is a matter of adding libntfs integration.  So, this is a bit more complicated.   After all, why not just add a standard library?  I scanned wiimc and wiiflow source code, and they seem to support libntfs without issue.  So, rather than spend time on confusing (sometimes belligerent) threads, I cut a diff last week with simple ntfs  library integration and sent it for review.   (see forks by hito16)   The pull request in its current state is NOT functional.  However from the effort, I was able to learn a bit more about the code and get feedback from the developer.  Here's what I learned thus far.

Fact 1.  I can see a lot of custom File system code in Nintendont.    Fat32 support was apparently made possible by trimming down the already lightweight PORTLIBS Fat32 libraries.  The Nintendont loader seems to do some in-memory filesystem patch ( which I admittedly don't fully understand yet).  Usb support is also apparently custom, the extent of which I'll know after I do a diff against the custom and stock usbstorage.c versions.

Developer comments: (reverberates with Fact 1): " [NTFS] wont work, the BIG BIG problem is the kernel which I said multiple times, if you look into the kernel folder you'll see that contains a different FAT library because while the games run we are in a different processor with much less memory and much less processing power so we cant just include a huge library like libntfs into it."

So now I have to weight a few data points.
CON:  A statement from the most authoritative source possible that libntfs is unfeasible.    
-  The guy has passion for the success of his project.  This is the guy that keeping what appears the last surviving active Wii homebrew, asking for nothing and getting next to NO help supporting it. 
 - This is the guy who understands the internals of Nintendont better than anyone.  Has more experience resolving constant stability problems and issues with emulator resource usage than anyone

CON: Confirmation that there was a lot of custom work required to make even FAT work.  Libntfs won't work without modification.

CON:  Most of the core homebrew projects  seemed to have died 3 years ago.  Interested expertise in this area will be hard to come by.

PRO: Well, its software.  Given infinite resources and infinite time, pretty much anything can be done.  Donating to the project probably won't hurt.

PRO:  I did write a basic boot.dol that simply lists files under ntfs0:/games using stock 2012/2013-ish usb+fat+ntfs libraries.  Setting up a devkitpro environment and building my first wii homebrew was pretty straightforward.   There's hope that someone with a stronger background than I can make something minimally functional.

Final thoughts.  I might continue working on this a bit more to see how far I can go. Perhaps one possible outcome is we have 2 versions of Nintendont.
1. stable version with Fat 32  - something you could play Zelda on to completion.
2. Bigkernel version with Fat32, NTFS and maybe usb DVD drives - something you can tinker with on most games, as long as you have a high expectation that the game will run out of memory before it starts, or crashes half way through.
An alternative outcome may be I'll learn enough of kernel memory profiling to share data which backs up FIX94's assertions.

Anyway, this is definitely an interesting project.  My thanks go out to Fix 94 for his unpaid work keeping Nintendont alive and continually improving the quality of this community project.

**Comment by hito16** [comment]
Probably old news for most, but after looking into the code and other projects a bit open-wii-flow, wiimc, etc), I see another "modern filesystem" timebomb looming.  All these projects work on MBR partition tables (which support drives up to 2TB)  but these projects not work with GPT.  Manufacturers of usb drives >2TB will almost certainly ship with GPT ntfs partitions, so +1 problem to solve for supporting newer 2016 drives.   Unrelated to NTFS feasibly, but factors I'll use to decide where my time would be best spent :  Native Wii U homebrews may be around the corner which should immediately remove the Nintendont kernel memory limitation for Wii U owners.  At the same time, SD prices are coming way down 64GB @ $20 = ~40 game images with 128-512GB now on the market.  And again, I'm pretty new at this. Any advice on how to rewrite a super small version of libNTFS with minimal effort would be welcomed.

**Comment by GerbilSoft** [comment]
Adding support for GPT is bound to be much simpler than adding support for NTFS. The only thing GPT does is it tells you where the partition starts, whereas NTFS has extents, journalling, etc.

The FatFS library doesn't support GPT natively, but it shouldn't be too hard to add a quick hack to check for a partition type 0xEE, at which point you'd then parse the GPT to find the actual FAT filesystem.

Some useful references:
* https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/block/partitions/efi.c - Linux kernel GPT handler; only 737 physical lines.
* https://en.wikipedia.org/wiki/GUID_Partition_Table

**Comment by greysondn** [comment]
> Any advice on how to rewrite a super small version of libNTFS with minimal effort would be welcomed

Depends, how small are we talking?

I am tied up in three projects but I am still subscribed to this thread and am willing to help as long as the asshat abstains from wasting my time again. I've not studied the architecture the Wii runs on but my degree was in game design and I know some 8086 assembly (basis for a LOT of assembler languages), some Arm7/Arm9 assembly (GBA/DS), and a lot of C++ (never guess what my language focus was). Conceivably between assembly and C/C++ (though preferably C if we're going for smallest size) we can get it down to a certain minimum.

That leaves:

* The filesystem spec
* valid points to hook the new code without breaking old code (ie; adding NTFS cannot break FAT)
* a reference implementation isn't the greatest thing ever but would go a long, long way - libntfs? Can we cut features out and still read or is Microsoft a worse failure than even I'd take potshots at? (NB: ext3 can generally be mounted as ext2 - can later versions of NTFS be safely treated as earlier NTFS? If so, we could chop out newer features as a last resort to save space.)

**Comment by hito16** [comment]
GerbilSoft / greysondn - great to hear interest from people willing to roll up their sleeves.  (GerbilSoft - saw your pull request for gpt support - cool).

greysondn - thx for the comments.  First off - good question:  "Depends, how small are we talking?"
 I should probably try and do a gdb meminfo dump and/or instrumentation of normal nintendont game emulation to have a better sense of how much headroom is left in the emulator/translator.  Ideally I shouldn't attempt to solve a problem that doesn't need solving.  The devkitppc gdb support looks very promising.

As to my request on advice, yeah your answers are in the vein I was looking for. Even better would be first hand knowledge on which feature sets are minimally needed to read files from a NTFS read only filesystem.  Ex from https://en.wikipedia.org/wiki/NTFS,  

[ feature -  my guess at whether it's needed for a RO mount]
4.2	Journaling - NO  ? - is this only needed for writes ? Is there any reason we'd need this for a RO file system?
4.3	Hard links - ? I see no value in this.  Is lack of this feature a show-stopper?
4.4	Alternate data streams (ADS) NO !
4.5	File compression NO !
4.6	Sparse files NO !
4.7	Volume Shadow Copy NO !
4.8	Transactions NO ?
4.9	Security ? - minimal stub implementations for ACL could be needed ? 
4.10	Encryption NO ! 
4.11	Quotas NO !
4.12	Reparse points NO !
4.13	Resizing NO !

Insight into whether these assumptions are true (or are complete) would definitely save time.  After going through the list, I see why linking in all these bloated features could cause concern.   My naive assumptions are:
 - the scope or work would be limited to simply reading partition tables, master tables, meta information and data blocks.  (Other features like journalling and permissions could be left out of scope?)
- The code would be new (not a reduction of libntfs) and look very similar to the ground-up, fat32 kernel code. 
And of course, fixing my bad assumptions is always appreciated.
