### ISSUE TITLE
z button not working

### ISSUE THREAD

**Issue by PacmanL** [FIX94/Nintendont#392]
i use a retrolink gamecube controller all of the other buttons work but not the z and the controller works its brand new and tested with nes emulators using z for select

**Comment by carnage702** [comment]
is it an usb controller or an gc port controller btw? also using wii with gc ports or wiiu with gc adapter?

**Comment by PacmanL** [comment]
its a usb controller

**Comment by carnage702** [comment]
then you need to make a correct controller ini, im guessing Z is not codeded correctly

**Comment by PacmanL** [comment]
how do i do that?

**Comment by carnage702** [comment]
need to use hidtest program to make a controller.ini your even lucky the controller works at all mayebe t found some similarity with another ini already submited and worked since every usb controller needs to make an ini for if you dont know how to make an ini ask here.

https://gbatemp.net/threads/nintendont-controller-configurations.355035/
