### ISSUE TITLE
Weird issue for some games related to Video Modes

### ISSUE THREAD

**Issue by cheatfreak47** [FIX94/Nintendont#398]
So, this is a strange one, but bear with me.

Basically, some games (In this example, BMX XXX) absolutely will not start if the Wii is set to 480p.
I believe this is due to the game crashing if it detects that there's a "component cable" in use (As gamecube games check this and display a "set 480p" menu of sorts.)

The solution to this, I suppose is to add an option that a spoof cable type option, the reason I suggest this is because, believe it or not- after the Wii is set to 480i, you can actually use Nintendont to force 480p and it will actually work (at least in the case of BMX XXX)

This problem is apparently present with several games according to the users of GBATemp waaaay back in 2015, and is a common cause for confusion for Wii U users due to the Wii U not really _having_ a video mode setting- with it by default being set to 480p internally- and it can only be modified with something like JoostinOnline's Settings Editor GUI.

What's even more bizarre is this issue extends to Dios Mios and even a real GameCube with the Component Cable, for BMX XXX at least.

Sources:
https://gbatemp.net/threads/nintendont.349258/page-801#post-5130535
https://gbatemp.net/threads/nintendont.349258/page-1115
https://gbatemp.net/threads/nintendont.349258/page-1116
https://www.avforums.com/threads/bmx-xxx-us-version-fails-to-load.78103/

**Comment by carnage702** [comment]
bmx-xxx has this issue fixed and patched, also you can also force the video on any mode you want on nintendont force video so yes you can force 480i if you want, altough bmxxxx is patched to work.

**Comment by cheatfreak47** [comment]
Well, I can confirm on the latest build this doesn't seem to be the case for a real wii with actual component cables, or one of those cheapo HDMI adapters.

Game black screens unless I set it to 480i- which is rather inconvenient.

**Comment by FIX94** [comment]
thats because you probably dont have memory card emulation enabled, that should make run just fine even with a wii set to 480p, simple reason for it is that EXI has the bit stored for video component flag.

**Comment by cheatfreak47** [comment]
@FIX94 Actually, I do have it enabled, setup for individual game memory cards, at 251 block size.

**Comment by FIX94** [comment]
Just from reading my code again I found the problem, it was perfectly fine when I coded it but somehow GerbilSoft messed it up 7 months ago in this commit:
https://github.com/FIX94/Nintendont/commit/e6e1c6a75683f46f23f13d36cbb11da1635ac2ac
If you look for the game "BMX XXX" it was shifted by 8 and now its by 24 which is completely wrong, just commited a new version which fixes it back to being shifted by 8 as it should be. Its quite simple why this game has that problem, the game is written so incredibly bad that they forgot to put in a handler when progressive can be displayed so the game just hardcrashes; the game also has several other flaws if you read its output debug log and I also was able to write a savegame exploit on a real gamecube for it; it is that bad:
https://github.com/FIX94/bmx_hax_gc
Note that even on a real gamecube if you owned component cables the game is unbootable, nintendont can only boot it because I made a patch just for it.
