### ISSUE TITLE
Dora the Explorer: Journey to the Purple Planet - Immediate Crash

### ISSUE THREAD

**Issue by cheatfreak47** [FIX94/Nintendont#400]
Been a while since I found a game to be totally incompatible, but this one seems to be. 
Game is reported as working back on v2.175, but I can't confirm whether or not that's accurate, since I don't have that version to test.

Verified the ISO and tried every combination of settings, including the defaults, and nothing seemed to get the game running- game also works fine under the last version of Dios Mios, so definitely not anything wrong with the ISO anything like that.

As soon as it's started the game locks up at a "Licensed by Nintendo" screen for whatever reason- if I try inputting the reset combo- it doesn't do anything. 

Here is the result of Log to File: https://hastebin.com/raw/vimefipawa
I tried booting it a few times with a couple different settings for the log.

**Comment by JellyMana** [comment]
Try downloading a tampered version of the rom, or modify it yourself manually.

**Comment by nictse2013** [comment]
first time to hear this game....

**Comment by cheatfreak47** [comment]
@JellyMana "Tampered version of the rom?"
Nintendont generally has the best compatibility with perfect 1:1 backups- how could tampering with  the ISO possibly be helpful?

For the curious, the last few days I've been actively seeking games that have bugs to report for Nintendont, the closer this software gets to 100% the better, after all.

**Comment by FIX94** [comment]
OK so I hooked some debug stuff into it and found that it crashed after doing a memcpy of some data which I couldnt trace back because it was quite deep into a function tree, but anyways the crash happened because of incorrect data so I put it into the special disc load exception where turok also is a part of which basically flushes out all the cache before handling the newly read data, no clue why those 2 games dont properly do that themselfs, I assume the cache maybe was smaller or something on gamecube so it all invalidated on its own back then.
