### ISSUE TITLE
Using Unofficial wii remotes  

### ISSUE THREAD

**Issue by zabrak** [FIX94/Nintendont#419]
I don't know anything about coding, but from what i have been able to find the HBC was able to add support to unofficial wii remote by recompiling the newest libogc svn. On the page i found this information it said this my be possible with other homebrew apps. I have no clue how do do this and was wondering if anyone had andy insight into this.

**Comment by carnage702** [comment]
nintendont does not use the standard bt stack while inside games due to memory contratins thats why most fake wiimotes on the nintendont app itself and dont work when games are running, nintendont runs on slower mode and bt stack was custom made to fit all the restraints nintendont has, maybe fix94 has some extra time to look at this someday to see if he can made the custom bt stack more compatible.

**Comment by zabrak** [comment]
Sorry if this isn't the place to ask.
Does this also still include Wii motion plus controls ?

**Comment by carnage702** [comment]
anything that uses the wiimote/wiimote plus is affected by fake wiimotes not using the standard calls the official wiimotes use.
