### ISSUE TITLE
Triforce BIOS not loading

### ISSUE THREAD

**Issue by SieKensou** [FIX94/Nintendont#420]
I have the Triforce bios with CRC-32 "D1883221" and renamed to segaboot.bin but the Triforce games starts normally without the Trifroce logo.
That BIOS file is the official BIOS from MAME, does it need some kind of fix like the games to run with Nintendont?

Thanks!

I tried a different BIOS file (I deleted it so I don't know the CRC-32, but I know it was different) and it didn't worked either...

**Comment by FIX94** [comment]
I guess I never properly explained how to get segaboot so I'll just do it in this issue and link it to people if they wonder how to get it, just so you know what you got there is just the boot loader that on a real triforce is responsible to actually load segaboot.
There are 3 very easily obtainable versions that I know of, note that the version doesnt really matter because in most cases the game settings etc are hardcoded in nintendont anyways to keep things consistent and safe so really its for looks.
-Version 2.17.0 can be found in Virtua Striker 4 (GDT-0013 and GDT-0015)
-Version 3.01.2 can be found in Virtua Striker 4 Ver. 2006 (GDT-0020 and GDT-0021)
-Version 3.11.2 can be found on the Triforce Firmware Update Disc (GDT-0022)
The first thing you have to do is get the actual gamecube image via my triforce-iso-extract tool which can be found over at https://github.com/FIX94/triforce-iso-extract
This will give you the usable gamecube image in "bin" form.
Open that gamecube image in something like GC-Tool or GCRebuilder.
-from the virtua striker games extract "segaboot.img1" from the "firm" folder
-from the triforce firmware update disc extract "segaboot.img1" from the image root
You can then just rename that to "segaboot.bin", it should be exactly 1MB (1048576 bytes) and have one of the following hashes:
-Version 2.17.0 SHA1: a3eabb012db09092300e796f5e2239973ce7b978
-Version 3.01.2 SHA1: 61aa40edbd179fe295850946639e2a4b33636b58
-Version 3.11.2 SHA1: 418411ee45a96d2ce585c3940a37608c491142ce
That "segaboot.bin" then just has to go onto the root of the device containing your triforce games and it should show up when you boot them.
The menu is also fully controllable, during its sequence you can press start at any time to get into its service menu and do whatever you want from there, just keep in mind nothing you set is saved or whatever ;)
I hope this helped you out.

**Comment by SieKensou** [comment]
Thank you! I will try that. Thanks for that useful information :)
With that there shouldn't be any problem. If I can't make it work I will let you know.

P.S.: Did you checked the Virtua Striker 2002 name? :P

**Comment by SieKensou** [comment]
Yes! Now it works pefect. Thanks for all the useful data and the explanation about how to make it work.

**Comment by FrostWolfZX** [comment]
This question was translated by Google translator, I'm Spanish and my English is questionable.



Hello, thanks for this post it helped me to start the triforce logo in Nintendont on my wii.

And sorry for this question, but is there a way to access the Mario kart arcade gp settings?, whether it's GP1 or GP2, I need to enter these options to be able to deactivate the Mario cards option, and in the case of GP2 commentator.  thank you for your answer.

**Comment by FrostWolfZX** [comment]
Forget it, I managed to access the configuration menu of the triforce just by pressing start on the controller.

**Comment by FrostWolfZX** [comment]
Apparently when I change something like deactivating the card mode and I return to the game I can't put credit in the triforce mode, even so if I deactivate it I can start just by pressing R, but apparently you are right that the settings are not saved, thanks anyway that you have published how to boot the bios of the triforce.

**Comment by PhirePhlame** [comment]
> 

I know the GP2 announcer toggle is part of the settings that get saved to the card, but since you want to turn that off, I don't actually know. That said, GP2's card system is infinitely more tolerable than 1's anyway, thanks to the simple fact that the devs wised up to how bad an idea it is to lock the player down to only ever using one character in a Mario Kart game.

**Comment by SavantSusi** [comment]
Which region/revision for virtua striker 4?
