### ISSUE TITLE
Option to change Home Button on CC to pause button. 

### ISSUE THREAD

**Issue by briantho** [FIX94/Nintendont#425]
Half the time when i give my friends a classic controller for use with nintendont I say "DO NOT TOUCH THE HOME BUTTON OR ELSE IT WILL RESET THE GAME." They understand, and even though i've told them several times, they still press it anyway by accident, when meaning to pause the game. Often times it will be in the middle of Melee, or Mario Party, or double dash. It's understandable, but i think the home button should be a pause button, or at least have the option in nintendont to change the home button to a pause button. I know the plus button is mapped to pause on a classic controller, but again sometimes people forget to press the + button instead of the home button during a game. It's very annoying. Anyway, if someone could either change the home button to a pause button and maybe assign the in-game reset button to say "minus" instead of home, that would be great. That, or just have an option to disable the in-game reset, when the home button is pressed. Thanks for understanding, and hope this can be fixed.

**Comment by carnage702** [comment]
So because your friends are dumb you want a new option on nintendont? lol even on wii/wiiu games the home button is never used on games unless you want to exit them, nintendont is clutered with options and adding basicaly useless option wont happen, you can recompile nintendont an rremove the home buttons altogether but this will never make it into officia nintendont.

**Comment by briantho** [comment]
..... ok, i really don't see why you don't really think this is worth doing. couldn't the in-game reset button just be changed to the minus button instead of the home button. Something along those lines would be much better in my opinion. The reason this I think this is important is because the classic controller is semi-mapped like a gamecube controller. Think of it like this, the gamecube start button is essentially right where the home button is on the classic controller. Having to remember to not press the home button, when you want to pause a game is kind of a pain, and i really think having it mapped to an in-game reset, isn't really a good idea. If you really don't think it's worth making the change for the official version of nintendont i guess i could compile it myself. The least that i ask is could you at least tell me what i would need to add/remove in the source in order to accomplish my goal of the home button act as a pause button/or just do nothing.

**Comment by carnage702** [comment]
the minus button is used to rotate the buttons on the cc/wiiupro controllers so they resemble the gc one, people have been using the minus ever since nintendont had the bt controllers support, so if that magicaly changed alot more people would exit nintendont becuase they press that button for over 2 years.

**Comment by briantho** [comment]
ok, so the minus button wont work, forgot that it was used for rotation. What about a button sequence for reset, like both triggers and the home button pressed at the same time to do the reset. Again, to me it seems that a "one button" reset is kinda a bad idea. To me it seems much more reasonable to have to enter a button sequence to reset, rather than having a accidental home button reset. I Don't really care about the button sequence either, just as long as it isn't a "one button, home reset". What do you think?

**Comment by carnage702** [comment]
like i said the home button on both wii and wiiu games is used to exit the game so it is on nintendont it wont be changedm you must educate your friends that is all, if you dislike that just get some gc controllers they have no home button.

**Comment by GrayGames** [comment]
I am very late to this thread, but I completely agree with @briantho. Having the ability to change the home button to another set of button combos would be very useful. When using the Wii,  normal people not only use the home button to reset, but also as a universal pause button since it does not lead you directly to the wii menu.

If this feature isn't "necessary" enough for the developers, I at least ask that a menu be added that says "Are you sure you would like to exit?" with yes or no options after the home button is pressed.

I also think an option that allows only Player 1 to exit the game would be useful. This would prevent accidental exits during playthroughs with little siblings that are not easily "educated"

**Comment by smdstudios** [comment]
There needs to be a way to remap Wiimotes and Classic controllers with a text file. The stock mappings are baked into the Nintendont executable and aren't user-modifiable.
