### ISSUE TITLE
Enhancement: GBA-GCN link emulation

### ISSUE THREAD

**Issue by MateoSebasBV** [FIX94/Nintendont#439]
In first place, thank you so much for developing Nintendont it's such an awesome app and as its name implies it's baffling why Nintendo didn't include its features built in on the Wii and Wii U. As for my question...Would it be possible to emulate the GBA-GCN link cable within Nintendont and then link it to an emulator such as VBA-M just like Dolphin does? I don't know just how possible would that but if it is it would be a really awesome and useful feature that would make Nintendont even better. Thanks for reading.

**Comment by carnage702** [comment]
Fix told me that its not possible becuase the second there would be a slight delay wich would happen imediatly the connection would fail. since you woud be linking through the network unlick dolphin where you link through the same device, you cant run nintendont and gba emulator at the same time on wii itself.

**Comment by Raflos10** [comment]
So I thought of an idea that might make this possible. 
What if we have all threads wait for the data response? So every time data should be sent to the GBA, the game freezes, then when the response is received, the game unfreezes, and repeat until message end. 
I realize the lag/stuttering would make the gba unusable as a controller option, but for games that only use it for a quick transfer it would be fine, right?
