### ISSUE TITLE
Configure my controller

### ISSUE THREAD

**Issue by Raidez** [FIX94/Nintendont#440]
Hello,

I buy that [controller](https://www.amazon.fr/gp/product/B00ND0E604/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1) solded by *Hori*.

All works fine, but in *Super Mario Sunshine* ("Yes, this game again :) "), I can't half-press R because buttons are digital.

3 questions:

- can I change buttons mapping ?
- can I mapping ZL+R to half-press R ?
- how can mapping my controller ?

Sorry for my bad language, I'm french

**Comment by carnage702** [comment]
it has been asked to death the thing is the hori battle sticks or whatever they are called dont have analog trigers and yet the **original Classic controller had analog triggers** and the **classic controller pro didnt** and someone at hori for some odd reason **instead of making the fightpads be identified as classic controller pros they made them tell the wii they are simple Classic controlers**, and nintendont does not have half press for classic controllers becuase they didint need half presses.

i hope you understood the reason why they dont have half presses, someone would need to had half presses to  then entire classic controller line, maybe if someday fix94 wakes up inspired it will happen, but i wouldnt hold my breath tough.
