### ISSUE TITLE
Pokemon XD: Gale of Darkness audio glitch

### ISSUE THREAD

**Issue by Pereb** [FIX94/Nintendont#447]
Pokemon XD: Gale of Darkness has an issue on certain tracks where cymbals sound choppy. Best example of this is the Mt Battle background music, also noticeable on the Normal and Cipher Peon battle themes.

Using default settings for everything except Native Control which is set to On. Hardware is a RVL-001 black Wii. Nintendont version is 4.448. Game region is NTSC-U.

Oddly enough Dolphin has the same issue (especially with HLE). 
Here's an audio file where you can hear what I'm talking about (it's from Dolphin but sounds basically the same, if you'd like me to record from hardware, let me know and I'll see what I can do) :
[Mt Battle.zip](https://github.com/FIX94/Nintendont/files/1236653/Mt.Battle.zip)

**Comment by carnage702** [comment]
what do you use to load your gc isos?

**Comment by Pereb** [comment]
CFG Loader, but same result with Nintendont from homebrew channel.

**Comment by carnage702** [comment]
i meant usb/SD  also i talked with fix94 and he says the wii outputs at a diference of 22hz from the actual gc , he and me listened to it and didnt hear anything choppy, im preety sure if you use dios mios it would sound the same since the wii does not output the same exact hz has the gc thats probably the reason of the sound diferent you migh hear.

**Comment by Pereb** [comment]
I see, thanks for the info. I was getting the same result via USB and SD btw.
