### ISSUE TITLE
USB Gecko Issues

### ISSUE THREAD

**Issue by Zephiles** [FIX94/Nintendont#448]
I finally got my USB Gecko working with Nintendont, but there are some issues with it.

To start off, I am using the latest version of Nintendont (I went and downloaded the most recent version and tested it right before making this post) and Gecko.NET 0.66.8. I have all of Nintendont's settings set to default, besides the option to turn the Debugger on.

When I initially load Nintendont with the USB Gecko inserted into Memory Card slot B, it either hangs at a black screen, or hangs at "Initializing IOS58...". The only way to get it to progress is to open Gecko.NET and repeatedly click on retry when it fails to connect. I have to do this multiple times for it to actually make any progress when loading, until it loads and gives the option to select either SD or USB.

Everything works fine here until I select the game. In this case I am booting the game in the disc slot. Once again, it hangs here, and I have to repeatedly click retry in Gecko.NET to get it to progress. It will then only start to fully work once the game is booted and Gecko.NET fully connects.

Once the game is running, everything seems to work fine. So the only problems are with Nintendont loading things while the USB Gecko is inserted into the Memory Card slot.

Edit: When I close Nintendont without disconnecting Gecko.NET, I can reboot Nintendont and it wont hang at all. It also still functions correctly without needing to reconnect, as long as I load the same game.

**Comment by FIX94** [comment]
This is perfectly normal, nintendont when it detects a usb gecko outputs a lot of debug text, while starting it you have to either take out the USB Gecko or keep GeckoReader open to let it read out all that text, otherwise it will wait forever on an answer on every debug text sent out (which is why clicking in Gecko.NET moved it along). Personally I just prefer it safely writing out the debug text over not waiting and potentially loosing out on debug info.

**Comment by Zephiles** [comment]
Alright. On another note, is it normal for frame advance to only work at 30 FPS? As in, it only seems to advance a frame when i press the button twice, and this is with a 60 FPS game.

**Comment by FIX94** [comment]
I dont think gecko.net is clever enough to know when a frame is actually over and probably relies on a breakpoint in the codehandler, nintendont potentially executes the codehandler multiple times a frame though depending on the game due to using multiple function hooks to ensure codehandler execution most situations so you may just see the same frame multiple times due to that in whatever game you are testing.

**Comment by Zephiles** [comment]
Well its consistently showing the same frame twice then.

**Comment by FIX94** [comment]
Well there are 2 hooks (OSSleepThread and PADRead) which in most games are both triggered at least once a frame so I guess that makes sense in a lot of cases.

**Comment by Zephiles** [comment]
Would it be possible to get it to only use one hook? Or does this require some extended coding changes or something?

**Comment by FIX94** [comment]
nintendont had issues when just using one hook for years so you better just keep it as is, better have more frames than suddenly missing frames.

**Comment by Zephiles** [comment]
Alright I suppose that's true. I also went back and double checked each frame to make sure none were actually being skipped, so there's no issues there.
