### ISSUE TITLE
Dualshock 4 won't exit Gamecube games since updating Nintendont

### ISSUE THREAD

**Issue by MondoGecko** [FIX94/Nintendont#451]
Ever since updating Nintendont from (I believe) v4.446 to v4.448, and updating my controllers.zip, I can't exit Gamecube games by pressing the Share button on a Dualshock 4 anymore. This used to work just fine before updating, and otherwise the controller is functioning perfectly. I just wish I could exit games with it still.

The .ini file associated with the controller appears to be pointing the "Power" function to the Share button, but I'm getting nothing out of it. There is no problem with the Share button itself as I have tested it on a PS4 and PC and the button is recognized and functions as it should.

**Comment by bombaygin** [comment]
did you solve the problem?

**Comment by aporcupine** [comment]
Same issue, I've also tried manually editing the controller.ini and chucking it on the SD & USB with no luck. Not the end of the world but it would be nice to exit with the controller.

**Comment by aporcupine** [comment]
So in further testing I changed the exit button to 6,01 (L1) and it exits just fine, so there must be an issue somewhere that is causing the share button to not work when in vWii mode (works fine in the HID test app in Wii U mode).

**Comment by aporcupine** [comment]
For anyone wanting a workaround that isn't a button that is easy to push by mistake (L1), then change the `Power` line in the  PS4 controller ini to:
```ini
Power=6,21
```
This will allow you to exit by pressing L1 + OPTIONS on the PS4!

**Comment by MondoGecko** [comment]
> For anyone wanting a workaround that isn't a button that is easy to push by mistake (L1), then change the `Power` line in the PS4 controller ini to:
> 
> ```ini
> Power=6,21
> ```
> 
> This will allow you to exit by pressing L1 + OPTIONS on the PS4!

**Comment by MondoGecko** [comment]
Thanks for the advice, tried what you said and it didn't work though. I tested the Dualshock 4 with HID test and the value you posted is in fact correct, but it just refuses to exit back to the Nintendont menu

**Comment by waterdragon78** [comment]
hey, how do I install controllers.zip on vwii?

**Comment by Medard22** [comment]
2021 and it´s still an issue. It´s driving me crazy.

**Comment by carnage702** [comment]
I just tested on 490 and if i hit share button i exit nintendont just fine with my dualshock 4 ID=054C, PID=05C4 power button is 6,10 8share button, do you guys have this ps4 controller or version 2  with VID=054C  PID=09CC ?

**Comment by Medard22** [comment]
I have the same DS4v1 as you, AFAIK the same nintendont build and it doesn't work. Tried running nintendont from both Homebrew launcher and USB loader Gx 😞

**Comment by carnage702** [comment]
> 
> 
> I have the same DS4v1 as you, AFAIK the same nintendont build and it doesn't work. Tried running nintendont from both Homebrew launcher and USB loader Gx 😞

works fine for me i just press share  and nintendont exists just fine on nintendont 490, maybe your controller.ini is bad or something? if i use a controller.ini on the root of my sd card or none at all i can exit just fine. for me the share button is reported as 6,10 on hid test, same for you?

**Comment by Medard22** [comment]
I checked the HID test, the 6,10 is the correct value. I am also using the right controller.ini file. Actually, I tried it even without the ini files as well. Hmm could you send me your version of nintendont dol and your ini files? I really don´t know why it doesn´t work.

**Comment by carnage702** [comment]
> 
> 
> I checked the HID test, the 6,10 is the correct value. I am also using the right controller.ini file. Actually, I tried it even without the ini files as well. Hmm could you send me your version of nintendont dol and your ini files? I really don´t know why it doesn´t work.

so i found out the issue since i had an old controller .ini before it was updated my power button wasnt at the botton of the file so to get the exit working again simply get your ps4 controller.ini then open it with notpad and cut the power button  Power=6,10 on the botton then after the digitallr=2 just paste the power exit there basically this

[DualShock 4v1]
VID=054C
PID=05C4
Polltype=1
DPAD=1
DigitalLR=2
Power=6,10
A=5,40
B=5,20
X=5,80
Y=5,10
Z=6,02
L=8,F0
R=9,F0
S=6,20
Left=5,06
Down=5,04
Right=5,02
Up=5,00
RightUp=5,01
DownRight=5,03
DownLeft=5,05
UpLeft=5,07
StickX=1
StickY=2
CStickX=3
CStickY=4
LAnalog=8
RAnalog=9

im guessing power exit cant be the last thing on a controller.ini for it to work or something.

**Comment by Medard22** [comment]
Oh man, that´s it! I checked my ini and yeah, the Power=6,10 was the last item on the list. I moved it after DigitalLR=2 as you suggested and it´s working now. THANK YOU! 
I used the inis from this repo, I had no idea it´s bugged :/ I guess someone should update them.

**Comment by carnage702** [comment]
> 
> 
> Oh man, that´s it! I checked my ini and yeah, the Power=6,10 was the last item on the list. I moved it after DigitalLR=2 as you suggested and it´s working now. THANK YOU!
> I used the inis from this repo, I had no idea it´s bugged :/ I guess someone should update them.

yeah i guess someone made a pull request and fix94 accepted it and no one really noticed since most people dont use the dualshcok 4 to play since no rumble while you have wiiu gc adapter+gc and dualshock 3 controller  with rumble and sensitive triggers or even wiiu pro controller with rumble + wireless or just gamepad for portable play, so it makes the dualshock 4 being like the 5 best controller to use at best xD

so anyone with this problem just do the following change.
