### ISSUE TITLE
GC Controll Adapter

### ISSUE THREAD

**Issue by HzFenix** [FIX94/Nintendont#491]
How can i play GC Games on my Wii U using the GC Controll adapter?
I've been reading and searching, and it doesn't show me on the settings board the HID USB option
It's on version v5.457

**Comment by carnage702** [comment]
that setting is long gone lol all you have to do is plug and play, if you choose to use the wiiu gamepad use ports 2 and up, if you choose not to use the wiiu gamepad you can use port 1 and up.

just plug it and it works.

**Comment by HzFenix** [comment]
Oh Jesus! I feel so stupid right now. Thank you so much

**Comment by weatmod** [comment]
> just plug it and it works.

no it doesn't
 i tried everything i can not get GC adapter to work
 do i need the official one? i have tried 2 adapters from Amazon neither one works
 why is there no official list of supported adapters or are they all supposed to "just work"
because i have tried 2 that work with   super smash wii u and they do not work with nintendon't using forwarder/inject ,  i start with wii mote and select do not use gamepad tv only ,  the game loads and say no controllers detected
