### ISSUE TITLE
Tip for two hid controls, with Nintendont

### ISSUE THREAD

**Issue by spielvan** [FIX94/Nintendont#493]
Hello Friend FIX94, a member there of the group MundoWiiHack (Cesar Avalos) commented a little about how to use more of a ps3 control with the retroarch of nintendo wii, even with a USB hub, I tested and worked perfectly, the question could implement this system with Nintendont, I will leave the tip here. a hug and success always.

What I did was:
I tested in versions of RetroArch 1.3.6 and 1.6.7

Download autoconfig http://buildbot.libretro.com/assets/frontend/autoconfig.zip

Inside the SD card, unzip and copy the autoconfig folder and its subdirectories to "/ apps / RetroArch /". That is in / apps / RetroArch / autotoconfig, there will be the android, dinput, hid folders ... Probably many of these folders are not necessary, but since they do not occupy almost anything, I chose to leave all there.
After that put the SD card in the Wii, and start the RetroArch.
In the RA settings:
To make sure the autoconfig will load:
Settings> INPUT> Autoconfig Enable: ON

Other settings I recommend:
Settings> INPUT> Toggle Menu Gamepad Combo: Start + Select
Settings> INPUT> All Users Control Menu: ON

Now we change the input driver:
Settings> Joypad Drive: hid

From here the wiimote will probably not work, but the usb controls should work just fine. I even tested using a USB hub to use up to 2 ps3 controls on the same usb port on the Wii. I tested the controls on the SNES emulator and it worked td blz.

**Comment by carnage702** [comment]
that thing is useless the issue is not how to read 2 hid controllers but how they are mescled up on nintendont incredibly complex controll code, we cant use normal libs that why even the bt controllers use a custom tiny lib because of memory constraints, everything about nintendont has to be custom made and the hid controller code is a huge mess of stuff writen in there, so it would require to rewrite the entire controller setup and then hid stuff , unless you can somehow convince fix94 to  loose quire afew hours doing so, no one will ever get it done.

also if you use nintendont you could use the wiiu gc adapter that is hid and supports 4 gc controllers, you ccant have anything better than that :P

**Comment by spielvan** [comment]
Thank you my dear for the answer, I will comment with friends who deal with programming, who knows someone has a tip, I will pass this your comment, to have a base on the nintendont and limitations, the more people better. Always a hug and success.

**Comment by markozutic** [comment]
my question is, if someone have tryed for example using 4 ps2 gamepads at same time, connect them all to  multitap adapter, and then go with ps2 to usb cable to wii. it should see all 4 right? or i hope it would :)

**Comment by rodrigoandrion** [comment]
> 

hey dude! I thanks a lot for this, but I think the link is dead
whats is the chance that you can re-upload it to us?
I'm like CRAZY trying to play Nintendont with 2 USB controllers
