### ISSUE TITLE
Triforce: Virtua Striker 4 Controller Calibration issues on GamePad

### ISSUE THREAD

**Issue by xXS4ALLx** [FIX94/Nintendont#510]
Not sure if it's me but the following two Triforce games:
**Virtua Striker 4 
Virtua Striker 4 ver.2006**

I've been testing Triforce games using the Nintendont direct first before I create a GC VC inject.
I first test by copying the ISO's to the SD CARD and just use the Nintendont forwarder on the WiiU to test the games.
Both games boot fine, however the controller is all screwed up, it seems the controller is stuck in the up position.

At the CALIBRATION boot screen, I move the LEFT analogue stick around in circles to calibrate on the GamePad, I even tried to move UP/DOWN/LEFT/RIGHT and I can see the numbers scroll through.
I've even tested with only minor movements until I can exit the screen with the + button, but still the game would still move up.

If I don't use GamePad mode, Wiimote + Classic Controller is fine.
In GamePad mode with 2nd player using Wiimote + Calssic Controller, P2 is fine, P1 still have issues.

**Forgot to Add:**
All other Triforce games work fine.

**Comment by Dil3mm4** [comment]
up

**Comment by olo85** [comment]
@xXS4ALLx Hi there, been following this discussion since I pretty got the same exact issue. Went on Nintendont though a forwarder found few days ago; I have no Wii remote control hence I can not access any vWii or other loader on my Wii U just yet.  Virtua Striker 4 v.2006 gets me the very same issue you sir described above if I control eveything through the clumsy Wii U Gamepad. And the game is basically impossible to play. Does anyone here have any possible solution or interest into a fix?
