### ISSUE TITLE
WiiU inject inquiry

### ISSUE THREAD

**Issue by CecilFF4** [FIX94/Nintendont#513]
If this is in the wrong place, please let me know.

WiiU GC injects can load the autoboot forwarder so Nintendont will load the game after it sets things up. Part of that setup surely includes initializing the USB for stuff like the gamecube adapter.

I'm wondering if a Wii inject can enact a similar process so that the gc adapter is allowed for Wii games like Mario Sunshine?

**Comment by carnage702** [comment]
no... nintendont emulates controllers for gc  so you can just use whatever controller is supported by it and emulated into a gc controller,you would need to make like usbloader or wiiflow emulate CC or gc controllers using hid devices to launch wii games wich they dont and probably never will becuase of lack of interest on very limited selection of games that are even compatible with those to begin with. if you want any of this you are better off asking on usbloader thread for someone to make controller emulation for wii games.

**Comment by CecilFF4** [comment]
I was only interested in USB initialization for Wii injects, not through USBLoader (for the one-HDD solution for the WiiU). I guess ultimately I was wondering if Nintendont could be structured to run Wii games and not just GC. If not, thank you for your time.

**Comment by carnage702** [comment]
no nintendont cant be used to run wii games , every wii app has usb initializiation its a trivial thing the issue with wii gaes is when wii games are running they use all the recources available wich leavues no recources for a secondary code to emulate controllers for instance, whie nintendont runs gc games wich dont use all the recources tahts why we have memory and cpu usage left to do some emulations like memory cards and controllers.

even on wiivc inject when a wii game runs it runs on vwii side wich means we have no ram or any decent memory to use becuase the wii app eats them all since wiiu memory is locked away on vwii and wiivc inject.
