### ISSUE TITLE
Issue with Mario DDR Dance mats

### ISSUE THREAD

**Issue by rog2e** [FIX94/Nintendont#527]
I am using the Wii with the dance mats plugged into the joystick ports. The dance mats work fine when I launch the game from the Gamecube disc. When I launch from Nintendont, the up and right arrows on the dance mat don't work properly.  For example when I am in the DDR menu screen if step on the up arrow it will make the selector go up but then the selector immediately goes back down. If step on the right arrow thselector will go to the right but immediately go back to the left. The left and down arrows work fine. If I use the gamecube joystick on port 1 it works fine.  I tried 2 different dance mats and as I mentioned it works fine when launching from gamecube disc.

**Comment by FIX94** [comment]
you can probably enable native controls to get it to work, I assume it has issues with the emulated controls as I do only emulate normal gc controllers. native controls basically passes through the wii ports directly to the game so things like that should work without an issue.

**Comment by rog2e** [comment]
Thanks FIX94. That worked!

**Comment by geogolem** [comment]
so i figured out how to use HID TEST on WIIU - I didnt realize I had to launch Super Smash Bros. First to initialize the gamecube usb adapter.

Turns out, with the dance mat connected, POS 08 and 09 are always set to FF FF..

when i unplug the mat and plug in a regular GC controller these bytes fluctuate from like numbers like 10 to close to FF depending on how depressed the L and R buttons are.

with the dance mat POS 04 05 06 07 are always zero (as far as I can tell) so this might be a way to determine if the connected device is a dance mat. Based on HID TEST, i am able to stand on left and right at the same time, and it changes the value accordingly. i.e. standing on both is different then standing on either one.

I am going to look more into the code and see if I can handle this case, but i have no idea how to build nintendont so I might need help with that, anyway - i think the info I found out might be useful.

**Comment by geogolem** [comment]
Image 1: Dance Mat (with nothing pressed)
![dancemat nothing pressed](https://user-images.githubusercontent.com/55031547/91156284-f8616400-e691-11ea-8780-dcae114f5b56.jpg)

Image 2: Regular GC controller (with nothing pressed)
![GC controller nothing pressed](https://user-images.githubusercontent.com/55031547/91156285-f8f9fa80-e691-11ea-86da-0ae868ee6877.PNG)

**Comment by geogolem** [comment]
bytes 02 and 03 change as I press buttons on the dance pad in a similar way to if i press the corresponding buttons (or combinations) on the GC controller. This includes combinations like up and right at the same time but the dance pad is also additionally able to differentiate cases where left and right are pressed simultaneously whereas this is no possible on the GC controller.. The issue is bytes 4, 5, 6, 7, 8 and 9 need to be ignored for the dance pad and treated as if they are in their neutral or natural positions (which I assume is similar to the regular GC controller with nothing pressed)... I think the fix is even easier then the one I proposed above.

**Comment by geogolem** [comment]
So I managed to get it built - and then i debugged it and it works! I opened a PR.
