### ISSUE TITLE
Dance Dance Revolution Mario Mix Dance Mat Left + Right issue

### ISSUE THREAD

**Issue by Shadowfied** [FIX94/Nintendont#572]
Dance Mats aren't working properly on Nintendont on Wii U with the official GameCube Adapter.

Left and right can't be pressed simultaneously, nor can one of them be held as the other is pressed, both making the game completely unplayable.

I've tried enabling Native Control as suggested in another issue, but this makes it even worse for me (when for example left is held, and right is pressed, it presses left again once right is released).

Any fix for this?

**Comment by carnage702** [comment]
native mode only works on wii s with gamecube ports not wiius, its probably the fault of the way it was designed the wiiu gc adapter, since we cant change how it reads comands.

**Comment by Shadowfied** [comment]
Well, is it the GameCube adapter that refuses left and right at the same time, or is that built in to Nintendont as it would normally be impossible on a controller?

**Comment by carnage702** [comment]
its impossible on a controller, you canot press left and right at same time on a dpad. the ddrpad emulates gc dpad.

**Comment by geogolem** [comment]
I don't mean to hit an old issue - but I am sort of trying to look into seeing if anything can be done to get Nintendont to handle the dance mat properly. It should be possible since it appears that it is possible with the dolphin emulator on PC to use the GC adapter with GC dance mat.. I made some comments here: https://github.com/FIX94/Nintendont/issues/527

I also found this in the source code but i am still sort of looking into this: 
https://github.com/dolphin-emu/dolphin/blob/e68e99ef7118cb73fde1f2ac9ec95b1a20c37909/Source/Core/Core/HW/SI/SI_DeviceDanceMat.cpp

**Comment by geogolem** [comment]
I managed to get this fixed with a very small code change to Nintendont. Most of the details are documented here: https://github.com/FIX94/Nintendont/issues/527

I opened a Pull request here: https://github.com/FIX94/Nintendont/pull/805
