### ISSUE TITLE
[Request] Could we get the option to set the Wii U Gamepad to anything other than Player 1/disable it once ingame? It makes using forwarders quite awkward.

### ISSUE THREAD

**Issue by Rust-and-Sunset** [FIX94/Nintendont#620]
The title sums it up, really - a lot of people launch Nintendont on Wii U via forwarders from the Wii U-mode Home Menu. When this is done via selecting the "Use Wii U Gamepad" option, Nintendont then automatically locks the Wii U Gamepad to the first controller slot, without the ability to reassign/turn it off entirely to replace Player 1's input with other controllers (USB GC adapter, Wii U Pro controller, etc).

While it's possible to get around this by booting the title in standard Wii mode, without Wii U Gamepad support, this means that the player needs a Wii remote to hand before the Wii U Home Menu will even allow you to boot the forwarder- which isn't always available.

An "Ignore Wii U Gamepad" option in Nintendont's settings would work around this, allowing people to use other controllers without having to launch with the Gamepad disconnected.

**Comment by NazarSurm** [comment]
Over a year late but here we are. I made a [fork](https://github.com/NazarSurm/Nintendont---No-gamepad-on-Player-1) with a small hack that disables the gamepad getting assigned to Player 1 even if you choose to "Use gamepad" in the WiiU system menu when launching a Nintendont forwarder. 

You can turn display off on the WiiU gamepad by holding down the power button on it for 5 sec. You can bring display back by pressing the power button again. Note, you won't be able to turn off your WiiU with the WiiU Gamepad while Nintendont is running since it won't accept any inputs from the Gamepad, power button included. 

Instead, you will need to use the power button on the console to power down

Alternatively, you can shut down Nintendont with the configurable button combo (default L+R+Z+Start on my gamecube controller) which will bring you back to the WiiU System Menu and enable inputs from the WiiU Gamepad again, allowing you to turn off the system with the WiiU Gamepad's power button.

**Comment by ealvarez2345** [comment]
Has there been any progress on the original idea posted here, or at least something similar? The fork is a nice solution to the issue of having the gamepad being forced to be player 1 but ideally it would just act as another classic controller/Wii U Pro controller so that it could still be assigned as a controller without having to be player 1 or letting it be turned off so that the wii remote wouldn't be needed to load up the game when using a pro controller.

**Comment by sailormoon** [comment]
This is fixed in #887
