### ISSUE TITLE
[Request] Add feature to support multiple HID controllers

### ISSUE THREAD

**Issue by ghost** [FIX94/Nintendont#702]
Please consider to Add feature to support multiple HID controllers, now only one USB HID controller can be connected, so cannot play multiplayer games. 

Wii U has homebrew (HID to VPAD) feature, but it does not work with Nintendont because it is application made for Wii and not Wii U, maybe it is possible to implement this feature?

3rd party Wii U controllers are also not supported, only original ones, but these are very hard to find, and will be harder in years to come.

**Comment by carnage702** [comment]
if you are on wiiu you already have some sort of wiiu controller like gamepad so you can play one player on wiiu gamepad and one on your hid device for multiplayer, heck if you buy a GC adapter wiiu or switch you can do 4 people with gc controllers because gc adapter is a single hid device with 4 ports so it can even do 4 players.

**Comment by Skindredas** [comment]
Thanks for reply, I will check it out, official pro controllers are very
costly. I have gamepad so I guess one player could use it other ps3
controller then...

2019-09-30, pr 19:59, pedro702 <notifications@github.com> rašė:

**Comment by olo85** [comment]
@carnage702 hi there, following the discussion and found it interesting to ask you directly then, if the gc adapter allows for multiplay on all the games or as I read works for Smash Bros. only, on Wii U and a forwader, not vWii. I basically want to play a 2 palyers match at Virtua Striker 4. ver.2006 where the bulky gamepad has calibration problems (analog gets stuck up on calibration no matter what I do, whereas in EVERY other situation it works smooth as hell, it means is a sort of rom issue, gamepad is mint). If the answer is yes it'd be perfect, since I got couple of original gc controllers from back in the days.

**Comment by carnage702** [comment]
> 
> 
> @carnage702 hi there, following the discussion and found it interesting to ask you directly then, if the gc adapter allows for multiplay on all the games or as I read works for Smash Bros. only, on Wii U and a forwarder, not vWii. I basically want to play a 2 palyers match at Virtua Striker 4. ver.2006 where the bulky gamepad has calibration problems (analog gets stuck up on calibration no matter what I do, whereas in EVERY other situation it works smooth as hell, it means is a sort of rom issue, gamepad is mint). If the answer is yes it'd be perfect, since I got couple of original gc controllers from back in the days.

yes you can use gc adapter 2 players or 4 if supported on vwii or wii, its still one adapter one code so it works.

**Comment by olo85** [comment]
Alright, thanks!
