### ISSUE TITLE
What actually is the classic controller (original) button mapping ?

### ISSUE THREAD

**Issue by Xberrypi** [FIX94/Nintendont#716]
I've searched everywhere, but I can't find a simple bit of documentation telling me which button on the classic controller corresponds to which button on the GameCube controller. Can someone help me out please ? 

Also, since the original classic controller does have analog triggers, can I use those with Nintendont ? So I don't have to buy a seperate controller that.

**Comment by carnage702** [comment]
lol the mapping is the exact same thing as the written buttons on the controller...

a=a
b=b
x=x
Y=y
etc

the only changes is Zr is gamecube Z and + is start button.

and yes analog l and r do work as intended and you can press - button to rotate x,y,a,b buttons since some people prefer the buttons switched to be more gc order,  so pressing - makes them rotate, pressing it again makes them normal.

also remember that classic controller pro has no alago triggers only the original. one does.

**Comment by Xberrypi** [comment]
Thanks ! Now I can enjoy playing the Wind waker without my anxiety bugging me :)
