### ISSUE TITLE
Nintendont on Wii, not recognizing Wii Motion Plus Controller

### ISSUE THREAD

**Issue by eat-sleep-code** [FIX94/Nintendont#725]
I have a Wii, running USB Loader GX (fully patched) and Nintendont.   I can play any Wii game fine.   When I attempt to play Mario Kart Double Dash, Nintendont starts and immediately the  Motion Plus controller's LEDs flash to illuminate all 4 LEDs.    I have no control of the game.

Is the Wii Motion Plus controller not supported by Nintendont?

**Comment by carnage702** [comment]
if its official yes it works, if its 3rd party most likely wont, but nintendont does not work with wiimote alone you need

wiimote+classic controller,wiimote+classic controller pro,wiimote+nunchuck, gc controller,wiiupro controller, hid usb controller(like ps3,ps4,etc, no xbox ones since they arent hid unless you buy an extra adapter).

**Comment by eat-sleep-code** [comment]
So, I just need to plug in the nunchuck and it will work?

**Comment by carnage702** [comment]
yes but nunchuck contros suck big time because not enough buttons and so on, i would advise getting a gc controller if your wii  has gc ports and if not atleast a classic controller to connect to the wiimote.

**Comment by eat-sleep-code** [comment]
I think my Wii just has two USB ports.

**Comment by carnage702** [comment]
> 
> 
> I think my Wii just has two USB ports.

so? one for the controller and one for your hdd, also if your wii has no native gc ports you can get a switch/wiiu gc  adapter and while it has 2 usb ports only one is needed since the second cable is just for rumble power which you can connect into something else or not at all, but if its easier for you just buy a wii classic controller that attaches to the wiimote.

**Comment by eat-sleep-code** [comment]
Thanks for the clarification!

**Comment by kleffa** [comment]
why third party wiimotes are not recognized? is too much dificult to make it work?

**Comment by carnage702** [comment]
> 
> 
> why third party wiimotes are not recognized? is too much dificult to make it work?

yes its very hard, since thrid partys/fakes just dont follow all the protocols the original ones do they skip steps send wrong data and whatever, so on many homebrew apps  apps thrid party/fake ones have issues.

**Comment by azispratama92** [comment]
i see, what about original wii mote with & classic controller attached is it possible to make it work with Nintendont?
