### ISSUE TITLE
Add Save States 

### ISSUE THREAD

**Issue by MeducaL** [FIX94/Nintendont#745]
Save states are just plain easier, kinda like wii64 has makes it easy and a lot simpler to play harder games or even games in general

**Comment by GerbilSoft** [comment]
This would require trapping all register writes, since not all registers can be read back to get their values.

Note that wii64 is a full emulator with emulated CPU and GPU, whereas games running on Nintendont run on the PowerPC CPU and ArtX/ATI GPU directly. Granted, hardware-level savestates have been done before, but it's much more difficult than with a full emulator. As an example, some EverDrive flash carts have savestates, but they have to monitor the bus for e.g. VDP register writes on Master System and Mega Drive, since VDP registers aren't normally readable.

**Comment by carnage702** [comment]
nintendont is not an emulator and memory is already as tight as it can get so this feature would be extremely hard to do even if possible.
