### ISSUE TITLE
Nintendont v6.489 freezes when trying to download something.

### ISSUE THREAD

**Issue by Ramshu** [FIX94/Nintendont#763]
When I try:
Download Nintendont
Download titles.txt
Download controllers.zip
Download gcn_md5.txt

The app starts the network and then freezes, forcing me to reset the Wii.

Thanks.
[sysCheckGX.txt](https://github.com/FIX94/Nintendont/files/4475388/sysCheckGX.txt)

**Comment by Ramshu** [comment]
``sysCheck GX v1.0.0 by Erik Spyder

sysCheck GX is running under IOS58 (rev 6176).

Console ID: CENSURED.
Region: PAL.
Hollywood v0x11.
Boot2 v4.
System Menu v514 (4.3E).
BC v6.
MIOS v10. 


Found 118 titles.
Found 42 IOS and 12 IOS Stubs on this console.

Priiloader is installed.


IOS  4 (rev 65280): Stub
IOS  9 (rev  1034)
IOS 10 (rev   768): Stub
IOS 11 (rev   256): Stub
IOS 12 (rev   526)
IOS 13 (rev  1032)
IOS 14 (rev  1032)
IOS 15 (rev  1032)
IOS 16 (rev   512): Stub
IOS 17 (rev  1032)
IOS 20 (rev   256): Stub
IOS 21 (rev  1039)
IOS 22 (rev  1294)
IOS 28 (rev  1807)
IOS 30 (rev  2816): Stub
IOS 31 (rev  3608): Trucha Bug, ES_Identify, NAND Access
IOS 33 (rev  3608)
IOS 34 (rev  3608)
IOS 35 (rev  3608)
IOS 36 (rev  3608): Trucha Bug, ES_Identify, NAND Access
IOS 37 (rev  5663)
IOS 38 (rev  4124)
IOS 40 (rev  3072): Stub
IOS 41 (rev  3607)
IOS 43 (rev  3607)
IOS 45 (rev  3607)
IOS 46 (rev  3607)
IOS 48 (rev  4124)
IOS 50 (rev  5120): Stub
IOS 51 (rev  4864): Stub
IOS 52 (rev  5888): Stub
IOS 53 (rev  5663)
IOS 55 (rev  5663)
IOS 56 (rev  5662)
IOS 57 (rev  5919)
IOS 58 (rev  6176): USB 2.0
IOS 60 (rev  6400): Stub
IOS 61 (rev  5662)
IOS 62 (rev  6430)
IOS 70 (rev  6912): Stub
IOS 80 (rev  6944)
IOS202 (rev 65535): Trucha Bug, ES_Identify, NAND Access, USB 2.0
IOS222 (rev 65535): Trucha Bug, ES_Identify, NAND Access, USB 2.0
IOS223 (rev 65535): Trucha Bug, ES_Identify, NAND Access, USB 2.0
IOS224 (rev 65535): Trucha Bug, ES_Identify, NAND Access, USB 2.0
IOS225 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS245 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS246 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS247 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS248 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS249 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS250 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS251 (rev 65535): Trucha Bug, ES_Identify, NAND Access
IOS254 (rev 65281)

Report generated on 2020-04-14.

**Comment by Ramshu** [comment]
I I think it may be a read / write error, because the nintendont settings are not saved either.

I have tried using different 2GB SD cards, formatted in Fat16 and Fat32, but the failure persists.

Eventually and without knowing how, sometimes when looking for updates for nintendont it works, but when restarting the app and trying again it fails.

Nintendont worked perfectly for me until version 5.485, then update directly to v6.489 and ran into this problem.

**Comment by carnage702** [comment]
486 was the last stable version, after adding bba there are issues like usb controllers crashing vwii injects and the download and such, its a known bug, but fix94 seems to have stopped working on this so finding someone to fix the  bugs will be extremely hard, i sugest going back to 486 if you dont plan on using bba features.

https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol?raw=true

**Comment by Ramshu** [comment]
> 
> 
> 486 was the last stable version, after adding bba there are issues like usb controllers crashing vwii injects and the download and such, its a known bug, but fix94 seems to have stopped working on this so finding someone to fix the bugs will be extremely hard, i sugest going back to 486 if you dont plan on using bba features.
> 
> https://github.com/FIX94/Nintendont/blob/7be1b6df41f07f39fd8e67dfd8be7b0b68209fc7/loader/loader.dol?raw=true

It makes sense, I was testing last night and sometimes the downloads worked and sometimes they didn't, which is an intermittent error.

It is a pity that FIX94 has abandoned the project ... In my opinion, it is the best GC loader for Wii.
The ideal would have been to leave it in a stable phase, in case someone wants to make a "reloaded" version in the future, they could start the project without major inherited errors.

I leave the ticket open so that it can serve as a guide for others, and they don't go crazy, like me, trying to solve it.

Thank you very much

**Comment by asheenlevrai** [comment]
same issue here.
also with USB disk.
every other time nintendont wont be able to read the usb disc. exit and restart nintendont fixes the issue

**Comment by Akorax** [comment]
I thought this happened to me as well. I started an update check:
1. Updating Nintendont
2. Initializing Network
3. Checking Latest Version
After that nothing happened so I left it on and went online to write a report about the issue but after a while I noticed it was done. So it turned out that it just took a really long time for it to complete.

**Comment by TL1882-official** [comment]
i'm having the same problem, i noticed if i left it for long enough it crashes and goes back to hbc

**Comment by wowitsjosh** [comment]
Figured I'd chime in here as well- I see this issue was closed, but I'm currently using version 6.498 on a 4.3U RVL-001 and this still seems to be a problem for me. Just as @TL1882-official mentioned, if I start an update for any of the options other than Nintendont, it'll show the message "Network Initialized" and never continue past that. When letting it sit for 5-10 minutes, it will eventually, consistently crash back to the HBC. I managed to grab a photo of the crash text that I'd be happy to share if anyone comes across this that can help.

I've tested this on both my home wifi and my phone's hotspot (also testing different network security settings with each), and with both I'm able to use network functionality just fine with other homebrew software (including writing to the SD/USB devices that are connected) so I can't image the problem is with my network connection or storage devices.
