### ISSUE TITLE
[request] [easy?] Add Wii mini support for HID controllers

### ISSUE THREAD

**Issue by Devnol** [FIX94/Nintendont#769]
Using Nintendont on the Wii mini works just fine. One problem though is that the hard drive on the Wii mini is mounted as `USB1:/` and not `USB:/` Is it possible to add a line of code or something to look for the controller.ini file in USB1:/ as well? I cannot play with A HID gamepad, which is the only way to play comfortably apart from the CC/CCP since the Wii mini doesn't have GameCube ports. I assume it's not that hard to do.

**Comment by carnage702** [comment]
you can buy a gc to wiimote adapter too works preety well

you loose rumble but still good https://www.amazon.com/Mayflash-Nintendo-GameCube-Controller-Adapter-Wii/dp/B00BS520SG

**Comment by CommandBlock6417** [comment]
Buying something to replace something else is not really my way of fixing things. Also, not everyone has the ability to do this.

**Comment by carnage702** [comment]
there is no active dev working on nintendont, so unless you find a codder this wont happen.

**Comment by CommandBlock6417** [comment]
Oh, ok. I didn't know that.

**Comment by 1ted59** [comment]
This seemed like a small change, so I tried making a quick edit so that the code that loads controller.ini checks USB1 as well. Let me know if this fixes this issue @CommandBlock6417 

This is currently untested as I don't have a Wii Mini to test on.
[loader.zip](https://github.com/FIX94/Nintendont/files/4610937/loader.zip)
