### ISSUE TITLE
NBA Live 2005 can't save

### ISSUE THREAD

**Issue by MarcoTheTaco** [FIX94/Nintendont#772]
Memory card emulation doesn't work, even when increasing the blocks it says there's not enough free space, any solution? (I'm using a game disc and no memory card)

**Comment by carnage702** [comment]
if you started with a smaller memory card first then you might need to go to your saves folder and delete it since changing the block wont delete if a previous title memory card file is already there with smaller block number.
so try go to your saves folder and delete the save file for that game then open nintendont, press b to settings choose a bigger one, i would avoid the 16mb one and go for the previous one 16mb option can make nintendont abit unstable on certain games.

**Comment by MarcoTheTaco** [comment]
![1588471349489572003351074342355](https://user-images.githubusercontent.com/64448861/80896859-b908a500-8ca7-11ea-88e2-c2a350d89dc2.jpg)
These are my save files, how can I know which one it is?

**Comment by MarcoTheTaco** [comment]
![211f86f8-bbdf-4dba-9b44-e34c1958e483](https://user-images.githubusercontent.com/64448861/80897904-7f896700-8cb2-11ea-9193-aae5ae6cacbe.gif)
Omg it worked thank uuu!! ^w^👣 this is me and my bro's favorite nba

I didn't have an issue with 251 blocks, I'd recommend it since this game uses a lot (saving a default season mode without playing any games uses 74)
