### ISSUE TITLE
Memory Card Encoding Compatibility

### ISSUE THREAD

**Issue by QbeRoot** [FIX94/Nintendont#776]
Hi,

It seems Nintendont ignores game region when saving to the memory card, and while I can see that being a useful feature for many users, it breaks compatibility with other loaders; if I create a save file for a Japanese game using Nintendont on my European Wii, that save file will not be recognized if I run the same game on, say, Gecko.

This is an issue for the Super Mario Sunshine speedrunning community, as:
- many players run the Japanese version on a non-Japanese console;
- a recently-allowed starting file for runs requires the use of practice codes, which everyone loads via Nintendont;
- runs themselves cannot be performed on Nintendont as it runs the game in Wii mode.

Is there any way that we can force the encoding to the game’s region (maybe using another Gecko code?), or could it be added as an option in Nintendont itself?

**Comment by carnage702** [comment]
if you set multi memory card to off nintendont will creat a single memory card fiule per game id that way there is no issues, if you want to save on a real memory card, afaik you cant have jap saves along with usa/pal saves because of  langauge reading of said game  as they can intreprete the data.

so yes turn multi to off use memory card emulation and make a small memory card per game, that way it never messes up.

**Comment by QbeRoot** [comment]
Thanks for replying but this isn’t what I meant: I want to create a Japanese file on a physical memory card, but Nintendont encodes it as ASCII instead of Shift-JIS. So when I later try to use that file with a different loader, the game expects Shift-JIS but finds ASCII, and it just tells me to format the memory card.

**Comment by carnage702** [comment]
nintendont uses the native save mode of the gamecube so that aint changing at all.
