### ISSUE TITLE
Where to go to make changes for Wii Remote + NC mapping changes?

### ISSUE THREAD

**Issue by Andreassoul** [FIX94/Nintendont#806]
where can I go in the code to make changes to the normal Wii Remote and NC key mappings? I read all the posts on: 

https://gbatemp.net/threads/nintendont-wiimote-nunchuck-support-discussions.371356/ 

But couldn't find where in the repository I could go to make some changes to the mappings I've wanted to do. Thanks!

**Comment by Njsmooth** [comment]
I would assume "loader\source\ppc\PADReadGC\source\PADReadGC.c", I've actually been trying to do the same thing but I've been having some compiling issues. Also, you'd need to find "// Nunchuck Buttons", which should be on line 756. Everything below is the configurations for each preset. Again, haven't been able to test it myself because I couldn't compile, but the code suggests it's the WiiMote & Nunchuck. This is my first post on GitHub, so sorry if I made any errors 😅

**Comment by geogolem** [comment]
if you are having trouble compiling, take a look at the code changes in my recent PR here: https://github.com/FIX94/Nintendont/pull/805

I added support for the dance mat, which is very close to the code you will need to change for button remapping. I also had trouble but did manage to get it built - the code changes necessary are also part of that PR (some are already in another PR) also, I had to set a couple environment variables which are also described in the commit message.. if you have trouble getting it to build or need help doing the button remapping, write here - and ill try to help. Im a noob at this - but I spent a whole night and did manage to get it to build.. so im happy to help if i can.
