### ISSUE TITLE
Power of Wii on Nintendont?

### ISSUE THREAD

**Issue by Richardblast** [FIX94/Nintendont#819]
hello despite having released my Wii console for years now I just try Nintendont and it is a marvel I noticed that the games run at more frames per second and they look even better with the composite cable my question is: how is this achieved? use some of the power of the Wii? in my little knowledge I know that the Wii Ram is different from the Gamecube I hope you can help me (without being so technical) and appreciate more your incredible work Greetings

**Comment by carnage702** [comment]
Basicaly the wii and the gamecube use the same exact cpu/gpu combo, the only diferences is ssdk diferences and the wii cpu is clocked much higher than the gc cpu.

So nintendont  is more like an intrepretaer, its not an emulator, while it emulates some things like disk reads,controller ports and some minor chips that arent acessible in wii mode  its far from an emulator as it can be.

Nintendont runs in wii mode with wii clock speed and translates gc calls into wii calls, since the cpu and gpu are the same as long as you translate them you get the same outcome except better since wii cpu is running much faster, which allows games to not drop so many frames and so on, in theory if you use a wiiu and make a vwii inject of nintendo and oveclock it to wiiu speed you probably can get almost every game at full fps speeds too how they were programmed without framedrops.

so all in all the power of the wii/wiiu is same cpu/gpu but highler clock rate that is all.

**Comment by Richardblast** [comment]
I thank you for the info the truth already knew for several years what you mention However, my doubt is oriented to the fact that your argument does not explain why when the gamecube is run on Wii due to backward compatibility there are no changes in performance, but there are changes with Nintendont. that is, when the "rom" is run through the official Wii channel it runs just like the original Gamecube but how or why Nintendont consumes other resources that Wii does not officially

**Comment by carnage702** [comment]
> 
> 
> I thank you for the info the truth already knew for several years what you mention However, my doubt is oriented to the fact that your argument does not explain why when the gamecube is run on Wii due to backward compatibility there are no changes in performance, but there are changes with Nintendont. that is, when the "rom" is run through the official Wii channel it runs just like the original Gamecube but how or why Nintendont consumes other resources that Wii does not officially

when you use backwards compatibility on the wii it is not run at wii clock speeds, thats why dios mios or official mios (gc mode) apps dont have improvements, nintendont does not run in mios therefore it can take advantage of the wii clock speed, while in mios the clock speed is limited to gc clock speed.

**Comment by Richardblast** [comment]
Thanks
Now  i see all clear!
