### ISSUE TITLE
(fake/SHANWAN) DualShock 3-controller causes Nintendont to power off the wii u 100% of the time.

### ISSUE THREAD

**Issue by QuinTeknoLife** [FIX94/Nintendont#833]
I have a fake SHANWAN DS3-controller from eBay which when plugged in causes my wii u to shut down entirely (red led), even in cases where any other controller is unresponsive. (i.e. an injected GC game blackscreening on boot seemingly having crashed, but the moment I plug the controller in the blue power-indicator blinks a couple of times before turning red turning off the system in the process)

I am running version 6.490

Outside of Nintendont (using HID-to-VPAD or the WUPS HID-to-VPAD plugin) the controller gets picked up as a DualShock 3 and works just fine.

**Comment by N-SPC700** [comment]
This has nothing to do with the software. Wii's and WiiU's are extremely sensitive to high power draw over USB, which is why the system is shutting off so much. Additionally, said controller wouldn't work with either system at all, unless the game has USB controller support (outside of the Gamecube to USB adapter Nintendo produced).
