### ISSUE TITLE
[Request] Selecting virtual memory cards

### ISSUE THREAD

**Issue by GeigerCounter** [FIX94/Nintendont#835]
Simple enough to understand. I have multiple memcard raws: some from Dolphin, some dumps of physical cards, some from . I'd like to be able to pick them from the Nintendont menu and load them into the virtual Slot A and Slot B as needed for the games in question. That way there's less swapping back and forth for memory card management.

If it's possible, I'd like also to be able to "plug in" the physical memory cards in the physical slots to their corresponding logical slot in order to be able to use a virtual memory card and a physical memory card at the same time. This for times such as playing Digimon World 4 with my brother and being able to use his physical memory card in Slot B to load his character while my virtual memory card is still loaded in Slot A to load mine.

**Comment by carnage702** [comment]
you will never be able to use a real one and a emulated one at the same time, because when using the emulated memory card all memory card functions are replaced and redirect so you cant do both at the same time.

As for choosing i dont see this ever happening since the paths and names are hardcoded into nintendont and nintendont doesnt have a file explorer so it can explore your sd/usb device and let you pick files , it would be just way too much trouble to add, you can use your pc or on the wii itself the homebrew app wiiexplorer and just change the card to the name nintendont searchs for before starting nintendont.

**Comment by GeigerCounter** [comment]
@carnage702 Yes, I _can_ do that... but I don't think having to eject the SD Card for memory card management is in any way ideal. Being able to handle this from within Nintendont would be better. ( Using WiiExplorer is not much better either, for the record. ) I respect that this is not something that the dev team wants to put effort into at the moment, but it's definitely a feature people would use.  So I guess expect a PR in the next few months after I've gone through the trouble. :) 

Too bad about not being able to use real and emulated memory cards at the same time, but it does make sense.
