### ISSUE TITLE
NTFS (please don't kill me)

### ISSUE THREAD

**Issue by asheenlevrai** [FIX94/Nintendont#841]
Hi :)

I looked it up and I know that nintendont developers said they will NEVER implement support for NTFS since it wouldn't make any sense and nobody would use it according to them. I read long threads including disputes and insults between various people and it got ugly... I don't want to stir any 5#ı† but...
Now, I came to realize that:
 - I can store and load all my homebrew apps on an NTFS HDD by using the HBFilter rather than the HBChannel
 - I can store and load all my Wii games on an NTFS HDD by using USB Loader GX (no longer need to split games larger than 4GB)

Unfortunately GC games need to be on a FAT32 or exFAT SD card since NTFS is not supported by nintendont nor is a 2nd partition or a 2nd HDD.
If nintendont did support NTFS one wouldn't need an SD card at all (one less POF?).
I don't know, it seems to make sense to me, but of course who am I to say anything...

I know NTFS support in nintendont will never be implemented :( but I am some kind of optimistic dreamer :)
You can close this now I guess. I hope I didn't make anyone mad by sharing my opinion.

Respectfully,
-a-
PS: please don't ban me or anything like that
PPS: GPT support would be nice too I guess but since neither HBC/HBF nor ULGX support it, what would be the point?

**Comment by carnage702** [comment]
Fix94 said that it would be too much memory to take on the nintendont dol file, nintendont already has a custom usb fat32 codding instead of the regular homebrew apps one due to memory constraints and ntfs would be much bigger, at least from what i remember him saying, so yeah not gonna happen and 99% of people just use fat32 for all homebrew stuff since most apps dont support ntfs.

**Comment by asheenlevrai** [comment]
Thanks for the kind reply :)
Have a great one
