### ISSUE TITLE
Does not work with my SN30PRO wirelessly

### ISSUE THREAD

**Issue by Hallowizer** [FIX94/Nintendont#852]
Hi! I ordered a retro receiver from 8bitdo, and I connected my SN30PRO to it to emulate a classic controller. I was able to control the Wii Menu and Virtual Console like normal, but it suddenly stopped working in Nintendont. The Wiimote it was connected to lit up all 4 lights, so the controller is definitely being detected by Nintendont, however, I cannot send any inputs from the Wiimote or the SN30PRO.

I did a bit more testing as well, and I am able to wire the controller to the Wii, however, my wire is not long enough for the whole room, so I have to sit very close to the TV to do that. The wireless receiver for USB does not work, with the same issues as the retro receiver.

I have also heard from others that third-party classic controllers tend to not work with Nintendont. Can Nintendont be updated to support them to the same degree as the Wii Menu?

**Comment by carnage702** [comment]
the anwser is yes and no, nintendont due to memory contraints runs with barebones bt controller and usb codding, so its light enough to run the rest of the app itself, so the bt stack nintendont uses is bare-bones and custom same for usb code, that is why most fake/third partys do not work on nintendont becuase it doesnt have the huge amount of codding to try and accept the hundreds of different types of connections and commands that several 3rd party's use, nintendont follows the comand protocols that the official controllers generate, if a fake/3rd party sends those comands in the correct order they will work, if they dont they often dont work.

**Comment by NeonLightning** [comment]
have you tried the different pairing modes for the sn30pro? i know on most retro emulation systems i've used it on it paired best in switch mode
