### ISSUE TITLE
Force GC resources

### ISSUE THREAD

**Issue by MutantAura** [FIX94/Nintendont#867]
Is there any way to force Nintendont into using regular GC clock speeds and memory etc. rather than Wii? 
I'm aware MIOS based loaders do this due to their MIOS requirement but it would be extremely helpful if Nintendont had a similar functionality. 

Using tools like this for GC game speedrunning is currently impossible due to the large gap between a real disk and how Nintendont runs ISO's. Games in general just run faster and have much less lag. This is possibly a fairly niche question however and if there is no support for this kind of thing then it's understandable.

**Comment by carnage702** [comment]
not possible... we cant slow down the wii cpu or else nintendont wont run, nintendont needs the extra cpu power to run on the backend to do well everything, ovciously games that had lag due to cpu bottleneck will run abit better and drop less frames but the game speed is the same.

only in mios does the wii cpu uses a diferent clock mode and even if someone managed to activate that then nintendont would crash becuase it wouldnt have the cpu speed to do the emulation of some  functions absent from wii mode like some sound stuff, audiostreaming,memory card emulation, controller emulation and whatnot.

**Comment by MutantAura** [comment]
Yea I had a feeling that the extra power would be tied into how Nintendont fundamental operates but I thought I'd pose the question. Thanks for the quick response.
