### ISSUE TITLE
Some Questions about Nintendont

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [FIX94/Nintendont#869]
on the github page under **Notes** it reads:

(1) The Wii and Wii U SD card slot is known to be slow. If you're using an SD card and are having performance issues, consider either using a USB SD reader or a USB hard drive.

(2) USB flash drives are known to be problematic.

(3) Nintendont runs best with storage devices formatted with 32 KB clusters. (Use either FAT32 or exFAT.)

For the first item, Are you recommending to put the Nintendont itself on a USB storage device ? or the games only ?

For the third item, you recommend to format the disk like below? If so, Do Wii games on the same storage work well ?

https://ibb.co/df1h0GQ

**Comment by GerbilSoft** [comment]
Nintendont itself isn't that big, so you can store the main program and related data files on an SD card. It's recommended to use a USB storage device for the actual disc images due to the SD slot limitations.

NTFS is not supported by Nintendont, and likely never will be due to the overhead of including an NTFS library.

FAT32 and exFAT are both supported:
* For FAT32, use 32 KB clusters.
* For exFAT, you could potentially use larger clusters (e.g. 128 KB), but this hasn't been widely tested.

**Comment by ReductoAdAbsurdum** [comment]
I also want to put some Wii games for use with Wiiflow lite on the same drive i put my GC games. Does Wiiflow Lite work better with FAT32 than NTFS also ?

**Comment by carnage702** [comment]
> 
> 
> I also want to put some Wii games for use with Wiiflow lite on the same drive i put my GC games. Does Wiiflow Lite work better with FAT32 than NTFS also ?

wiiflow and usloader gx can read wii isos on fat32 just fine same as nintendont also this is for issues and not for questions, questions like theis you do on nintendont main thread on gbatemp forum.
