### ISSUE TITLE
Pokemon Colosseum black screen when loading cheats

### ISSUE THREAD

**Issue by omegakilla** [FIX94/Nintendont#892]
every time I try loading Pokemon Colosseum with cheats the game crashes and stays on a black screen I'm running the latest version of nintendont and I don't know what to do. I tried looking everywhere but couldn't find an answer.
also I'm playing on a normal wii

**Comment by carnage702** [comment]
nintendont is not compatible with every gamecube cheat, due to running gc games in wii mode there are many memory addresses that aren't in the same place, so your cheats probably are targeting a different address that  changes some nintendont function instead of what you want to change, you would need to be a coder and using a usb gecko on wii and see where you are using the cheat and if it was moved in nintendont.

Some cheats work, some dont it depends if  the area you are patching as maintained the same addresses on nintendont vs gamecube, there isn't much to be done, you would have to manually change that address for nintendont.
