### ISSUE TITLE
Blackscreen issue with Wii VC on European WiiUs w/recent commits

### ISSUE THREAD

**Issue by AuroraWright** [FIX94/Nintendont#902]
Recent commits have the following behavior with European WiiUs: when a Nintendont Wii VC inject is launched, if the console *has not* soft rebooted from Wii mode since the last shutdown, it blackscreens/hangs and you can only pull the power plug.
It reminds me of what happens with displaying the Nintendont main menu (which will be shown garbled on European consoles on Wii VC unless you soft rebooted from WIi mode before).
I pinpointed it to commenting this line: https://github.com/FIX94/Nintendont/blob/master/loader/source/main.c#L850 . A local build with it uncommented works fine. I have no idea why Nintendont has such issues with initializing video on European consoles specifically and if this is a hack, but maybe it's worth investigating

**Comment by carnage702** [comment]
i have an european wiiu and i have used it since day one and never had any single issues with anything and i was a nintendont tester on wiiu since day one so yeah nothing to do with this, its always a mystery some wiius work some dont, it doesnt have anything with being european or not at all.

heck there is no european videomode an english europen wiiu is the exact same as an english american wiiu with a region lock and that is all.

**Comment by AuroraWright** [comment]
Not sure why I was remembering the video issues being related to European consoles, but my mistake. They were reported before however: https://github.com/FIX94/Nintendont/issues/487 . I verified that uncommenting that line I indicated makes injects work again on coldboot on my console (they stopped working since you commented them in https://github.com/FIX94/Nintendont/commit/d1b29b0d08899ca8e2cd4cd7899d9dd2fda281df#diff-3887ffbc8b7b36deea9ed3bb5783ef8580d9534fe8196badf2088699f3b5ba68L847 ).
Do you also use a HDMI cable by any chance? (I tested on two TVs, both via HDMI and 1080p as WiiU-mode video mode). Or it could be related to console revision maybe (?).

**Comment by carnage702** [comment]
> Not sure why I was remembering the video issues being related to European consoles, but my mistake. They were reported before however: #487 . I verified that uncommenting that line I indicated makes injects work again on coldboot on my console (they stopped working since you commented them in [d1b29b0#diff-3887ffbc8b7b36deea9ed3bb5783ef8580d9534fe8196badf2088699f3b5ba68L847](https://github.com/FIX94/Nintendont/commit/d1b29b0d08899ca8e2cd4cd7899d9dd2fda281df#diff-3887ffbc8b7b36deea9ed3bb5783ef8580d9534fe8196badf2088699f3b5ba68L847) ).
> Do you also use a HDMI cable by any chance? (I tested on two TVs, both via HDMI and 1080p as WiiU-mode video mode). Or it could be related to console revision maybe (?).
> 
> I also tried messing a bit with the loader source and calling Initialise() as the first thing in main() and commenting out everything but GRRLIB_Init() and the menu drawing stuff, and I noticed on coldboot the menu is rendered incorrectly. It would seem that GRRLIB_Init() works incorrectly on some consoles/configurations which leads to these issues. I tried using the latest version of GRRLIB_Init() from the latest release of the library to no avail. Sadly that's as far as I can get as low level Wii GPU init stuff flies over my head honestly

Of course I use the HDMI cable, it's a wiiu not a Wii I'm not gonna use component cables, my wiiu is the 32 gb one and afaik there are no wiiu revisions, also I didn't commented in those lines, they are commented out since I guess more people have more issues with their in than out, for me it makes no difference, never ever had any issue going in with injects. Like I said since day one it works well for some people and not for others, no one found the exact reason, some people even have black screens using injects of hombrew channel instead of nintendont, so I guess it's some wiiu issues that were never ironed out.
