### ISSUE TITLE
Resident Evil 2 Nintendont freeze?

### ISSUE THREAD

**Issue by Ledoeye** [FIX94/Nintendont#903]
Hello there, i been playing a lot of games through nintendont and this is the first time i found an issue. Resident Evil 2 freezes everytime i shoot the zombies with the shotgun you pick up from the shop guy early game. Is there a workaround for this?

**Comment by carnage702** [comment]
take a picture of your nintendont settings and check your iso md5, you either have forced settings that the game doesnt like or a bad iso.

**Comment by Ledoeye** [comment]
There's the picture : [https://ibb.co/TwV796p?fbclid=IwAR2kCj3L8npXyAYdqrCVB2BmCom5F4jYHB4UwlVnvwJxPOE4yKzmRmfxWjY](url) I forgot to say that i use the USB loader not sure if there's any difference than running directly from nintendont instead.

**Comment by Ledoeye** [comment]
Just checked the MD5 of the ISO and it's a bit different than the one at GAMETDB website.

**Comment by Ledoeye** [comment]
Just loaded the game through and SD and it didn't freeze. It froze 3 times when i ran through my 1TBHDD. So i guess the problem might be my HDD? This HDD was in the basement for a good 4 years or so lol maybe it's broken? Do you guys have any recommendations?

**Comment by carnage702** [comment]
i cant see your picture so i cant help, probably not the hdd, usbloader has its own forced settings and im guessing they arent being saved when you moved the iso try starting nintendont directly from homebrew channel instead of usbloader and try it on the hdd im sure it will work.

Do remenber any setting can break a game, most games work with forced stuff but some dont like it, not even something simple like width and such can break games

to get best compatibility put everything off or auto except memory card emulation(if you need it) and try it first.

**Comment by Ledoeye** [comment]
I never really force any settings. Can you see the picture now : https://ibb.co/TwV796p?fbclid=IwAR2kCj3L8npXyAYdqrCVB2BmCom5F4jYHB4UwlVnvwJxPOE4yKzmRmfxWjY

Lol i just checked my HDD and it's actually a Seagate 4 TB, really thought it was 1. Is it bad?

**Comment by carnage702** [comment]
> I never really force any settings. Can you see the picture now : https://ibb.co/TwV796p?fbclid=IwAR2kCj3L8npXyAYdqrCVB2BmCom5F4jYHB4UwlVnvwJxPOE4yKzmRmfxWjY
> 
> Lol i just checked my HDD and it's actually a Seagate 4 TB, really thought it was 1. Is it bad?

Max size recommended for Wii i think it's 1tb max 2tb  but those settings means you aren't even forcing mc emulation, are you using a real memory card?
