### ISSUE TITLE
Can I make xbox 360 controllers compatible with Nintendont?

### ISSUE THREAD

**Issue by Latiascringesatyou** [FIX94/Nintendont#915]
After the recent discovery that my classic controller was not in fact a real model and would not work on nintendont (or the isos in the nintendont, I can still control with the classic controller on nintendont itself [like the settings]) I didn't want to spend my money on another classic controller, so I was wondering if nintendont or any add-on file for nintendont can be compatible with xbox 360 controllers. If there is a way, can somebody walk me through on how to make xbox 360 controllers work on nintendont? here are some images of my controller (and the thing connecting it to the usb port) ![image](https://user-images.githubusercontent.com/87508408/126048595-0d5fd548-2880-4184-bf76-49faa4a5bb19.jpeg) ![image](https://user-images.githubusercontent.com/87508408/126048607-1888d388-0884-47f3-b85d-566a6e7cdf22.jpeg) ![image](https://user-images.githubusercontent.com/87508408/126048618-ab43bd9c-c91c-4821-bfa0-6f07ba54bddd.jpeg)

**Comment by carnage702** [comment]
Nintendont uses hid code for usb controllers, xbox controllers are not hid they are xinput based so they arent supported, there is a fan made mod where they used xinput over hid, this is not official nintendont so use it at your own and dont ask to solve the mod errors here

https://github.com/revvv/Nintendont-XBOX360

not sure if your xbox controller will even work since he says only one model is supported see that repo.
