### ISSUE TITLE
Sonic Riders (GXEE8P) Gecko code issues

### ISSUE THREAD

**Issue by SaladHues** [FIX94/Nintendont#920]
Hi,
For some reason Sonic Riders has issues with loading gecko codes, causing the game to freeze the moment a code is executed. I have tried several codes with no luck and have verified my game isn't corrupted. I'm wondering if a workaround is possible for this?

**Comment by carnage702** [comment]
nintendont has some memory addresses shifted due to working on wii mode so not all codes/hacks will work because there are memory areas that will crash nintendont if called upon because the game is not running there anymore, but running on another addresses, you would have to custom made some cheats and hacks if they dont work normally to be nintendont specific.
