### ISSUE TITLE
Memcard emulation cannot save 

### ISSUE THREAD

**Issue by V3R30R** [FIX94/Nintendont#938]
When starting up my game on Nintendont,  it tells me that I have no space on Card A to save my game. I have Multi on and it works when I turn that off but my saves are gone. And when I play the game through Wiiflow it works too but it doesn't have my saves when playing from Nintendont itself. I'm hoping my only options don't require me to start the games over lol

**Comment by carnage702** [comment]
this is not an issue just lack of common sense by you.

im guessing you never used a console that had real memory cards like the gc or ps2? if its full its because its full...

Nintendont has 2 options multi yes or no

with multi yes every game you start gets saved on a single memory card file so if you choose a small size it will fill up fast 

multi no nintendont crates a single memory per game wich means it never gets full becuase each game has its own dedicated memory card file.

So you got 2 options
either create a bigger multi memory card or just start using multi no and each game gets its own memory card file and it will never fill up.

If you go with the first option just go to your saves folder and copy to your pc the nintendont raw file(memory card to your pc) choose a bigger size multi and start a game so nintendont can creat one .

then download dolphin on pc(wii/gc emulator) then on dolphin settings you got memory card management option you load up the old multi and the new multi and just copy the saves from the smaller to the bigger one.
**Even then this could be full in the long term since its a shared memory card, the single option(multi off) is much better and safer in case of corruption you only loose one save vs all saves.**


**If you choose the one memory card per game like most people use**  you need to know the gameids of the games you got saved, you can see the ids  on nintendont menu when seeing the game list 

what you do is copy your multi save file over and over so you get as many copys of the file as games you have saved on there and then rename each one  for the game id of each game(only creat the game ids manualy for the games you got saved already and not for games you never saved, those will be created automatically after.

for instance GCEP.raw   only the first 4 letters are needed and then turn multi to off in the settings, and every new game you will start that doesnt have a save will be created its own memory card file and no need to worry if its ever gonna be full.

**Comment by V3R30R** [comment]
> this is not an issue just lack of common sense by you.
> 
> im guessing you never used a console that had real memory cards like the gc or ps2? if its full its because its full...
> 
> Nintendont has 2 options multi yes or no
> 
> with multi yes every game you start gets saved on a single memory card file so if you choose a small size it will fill up fast
> 
> multi no nintendont crates a single memory per game wich means it never gets full becuase each game has its own dedicated memory card file.
> 
> So you got 2 options either create a bigger multi memory card or just start using multi no and each game gets its own memory card file and it will never fill up.
> 
> If you go with the first option just go to your saves folder and copy to your pc the nintendont raw file(memory card to your pc) choose a bigger size multi and start a game so nintendont can creat one .
> 
> then download dolphin on pc(wii/gc emulator) then on dolphin settings you got memory card management option you load up the old multi and the new multi and just copy the saves from the smaller to the bigger one. **Even then this could be full in the long term since its a shared memory card, the single option(multi off) is much better and safer in case of corruption you only loose one save vs all saves.**
> 
> **If you choose the one memory card per game like most people use** you need to know the gameids of the games you got saved, you can see the ids on nintendont menu when seeing the game list
> 
> what you do is copy your multi save file over and over so you get as many copys of the file as games you have saved on there and then rename each one for the game id of each game(only creat the game ids manualy for the games you got saved already and not for games you never saved, those will be created automatically after.
> 
> for instance GCEP.raw only the first 4 letters are needed and then turn multi to off in the settings, and every new game you will start that doesnt have a save will be created its own memory card file and no need to worry if its ever gonna be full.

I appreciate your response even though you kind of attacked me at first lol. I have used a ps2 and gamecube before so that wasn't my issue, my issue was how to find and fix my saved games which you pretty much showed me so thank you for that part at least.

**Comment by V3R30R** [comment]
> this is not an issue just lack of common sense by you.
> 
> im guessing you never used a console that had real memory cards like the gc or ps2? if its full its because its full...
> 
> Nintendont has 2 options multi yes or no
> 
> with multi yes every game you start gets saved on a single memory card file so if you choose a small size it will fill up fast
> 
> multi no nintendont crates a single memory per game wich means it never gets full becuase each game has its own dedicated memory card file.
> 
> So you got 2 options either create a bigger multi memory card or just start using multi no and each game gets its own memory card file and it will never fill up.
> 
> If you go with the first option just go to your saves folder and copy to your pc the nintendont raw file(memory card to your pc) choose a bigger size multi and start a game so nintendont can creat one .
> 
> then download dolphin on pc(wii/gc emulator) then on dolphin settings you got memory card management option you load up the old multi and the new multi and just copy the saves from the smaller to the bigger one. **Even then this could be full in the long term since its a shared memory card, the single option(multi off) is much better and safer in case of corruption you only loose one save vs all saves.**
> 
> **If you choose the one memory card per game like most people use** you need to know the gameids of the games you got saved, you can see the ids on nintendont menu when seeing the game list
> 
> what you do is copy your multi save file over and over so you get as many copys of the file as games you have saved on there and then rename each one for the game id of each game(only creat the game ids manualy for the games you got saved already and not for games you never saved, those will be created automatically after.
> 
> for instance GCEP.raw only the first 4 letters are needed and then turn multi to off in the settings, and every new game you will start that doesnt have a save will be created its own memory card file and no need to worry if its ever gonna be full.

Thank you for your help. I have used Memory Cards before but I couldn't figure out where my saves were and how to make more space that didn't involve me having to start the games over. Thank you again
