### ISSUE TITLE
Menu button terminating game; causing loss of game progress. 

### ISSUE THREAD

**Issue by git2358** [FIX94/Nintendont#940]
A small but significant discussion on a discord about changing the way the menu button terminates GameCube games and returns to the wii u menu.

This happens so instant and causes accidental game save loss.

Suggestion/Request to change the menu press to a press and hold for 2-3 seconds to avoid accidentally terminating a game; and then returning to the wii u Home Screen as normal.

We hope this to be an easy and quick thing to be implemented if considered.

**Comment by carnage702** [comment]
you can fork nintendont for yourself and mod that, the exit button is home or a button combo no one should hit home by accident since every controller that has home already has + and - and no one on any game wii or otherwise would press home to acess any menu on any game, home is always a buitton to get out of the game itself,  or do the weirdest button combo to make it exit by accident so this is a personal thing for you and anyone that wants, nintendont is an open project your free to mod it yourself.
