### ISSUE TITLE
Nintendont exit/crash if press "+" on procontroller

### ISSUE THREAD

**Issue by yanz** [FIX94/Nintendont#955]
Using injected VC to load Nintendont from an installed title in the wiiu menu.   
  
Works 100% fine with gamepad.   
If connects aftermarket pro controller and press "+" it seems to trigger "home" or it does trigger Nintendont to exit or crash idk.   
  
Looks like it exits properly as it will reload my wiiu instead of being frozen still.   
  
After market controller is "Icon ICN500"

**Comment by carnage702** [comment]
there is nothing to be done if your 3rd party controller + says to nintendont its the home menu, which is the signal that its sending, nintendont has general code for classic controller and wiiupro controllers and such, 3rd party stuff/fake ones is never recommended because they send weird signals, you cant fix that whiteout breaking the legit controllers.

**Comment by yanz** [comment]
The controller works as intended if i use the forwarder to open Nintendont, its just with the injected VC that it happens 

I used teconmoon vc injector.

**Comment by carnage702** [comment]
there is no controller difference when starting an inject or a forwarder the controller code is the exact same, unless you somehow made an inject wihch has its own nintendont boot.dol inside and its an outdated version when you start an inject vs when start the forwarder where it actually loads the boot.dol
