### ISSUE TITLE
Will not update files

### ISSUE THREAD

**Issue by Sollymans11** [FIX94/Nintendont#956]
![16401296240063632564633209916962](https://user-images.githubusercontent.com/96503550/147011091-e0052a26-b137-4691-b449-8ed0cb03a07f.jpg)
I have been trying to update my files on Nintendont and it would just freeze. While I was writing this, I finally got an error that was shown in the image. Would I have to do this from a computer or just keep trying?
I was trying to update the titles.txt and controllers.zip files.

**Comment by Duknine2** [comment]
I'm here to report that I also have the same problem. I've read reports of other people having managed to update, they were able to download the background. In my case, whenever I try to update, this app crashes and only exits when the console is forcibly turned off.

**Comment by carnage702** [comment]
> I'm here to report that I also have the same problem. I've read reports of other people having managed to update, they were able to download the background. In my case, whenever I try to update, this app crashes and only exits when the console is forcibly turned off.

official nintendont does not download any backgrounds so this isnt a issue for the official app, whatever isnt official its not to be reported on the official github.

**Comment by cyberstudio10** [comment]
Did some cursory look. Changed the code to point to my own http (not https) server and hosted the files (titles.txt et al) and that worked fine except

- Can't extract controllers.zip maybe because I already have the controllers directory and the files and it refuses to overwrite them.
- I didn't host loader.dol and that should be a 404 Not Found, but I see a black screen of death and it reloads.

Next, with wget, I did a slew of experiments with HTTP GET headers, to see if there are certain missing fields causing github to just throw away the request. Things like User-Agent, Accept, etc. Turns out nothing found, github is very lenient. You don't have to tell it what browser you are, or referrer, or just about anything at all.

When you add the 2 cursory data points together it points to something wrong with SSL. Anyone wants to drill down from here?
