### ISSUE TITLE
turning off unintentionally

### ISSUE THREAD

**Issue by Duknine2** [FIX94/Nintendont#965]
There are games that are shutting down every time it is started. The first one is Freedom Fighters, before it turned off automatically when started by USB Loader GX and now the same happens when it is directly by Nintendont. Another game that made me go public to report this very annoying problem is Mission Impossible Operation Surma, in this it happened in both cases (if it happens through Nintendont it will happen in any other pre-configured Loader). I'm not sure if I used that tool to shrink the size of the ISOs, but if so, I don't think it was because of that because I can play other games also with reduced size like Mario Kart Double Dash and Super Mario Sunshine, in addition to others.
the version I use is 6492 MMMod.

**Comment by carnage702** [comment]
First if you are using a mod then you shouldn't report mod issues here since its not official, the latest official nintendont is 6.498.

Second every game is different if a game works shrunken or with certain forced setting, others might not, it depends on how the game is coded, every forced setting is an hack and can crash games and if an iso is shrunken badly and has audiostreaming it will also crash.

Then again you are not using official nintendont so this has no place here.
