### ISSUE TITLE
Questions about Emulated Memory Cards

### ISSUE THREAD

**Issue by JordanB500** [FIX94/Nintendont#973]
Hello I have been using nintendont + usbloadergx to play gamecube games without issue and I have been playing them with an emulated memory card since my real ones have a tendency to fail or to corrupt easily and I have only used 8mb .raw files,  it was only recently that I was told that you can use a  separate file for slot b as an emulated memory card.

I have also been told that 16mb memory cards can cause problems and I was wondering if there is a file size between 16mb and 8mb that will still function without issue or do I need to use 8mb or less all the time?

**Comment by carnage702** [comment]
well slob b wasnt added by main nintendont devs, it was a pull request so im not sure about limitations i only know slot b should be small due to memory limitations.

If you really cared about preserving saves and  such you wouldnt use 8mb mcemu, instead you should use a memory card per game option using 251 blocks , that way each game would get its own dedicated memory card raw file and then if it would end up corrupting  you would loose only that game and no other.

**Comment by JordanB500** [comment]
I have never had problems with emulated memory card being corrupted i just wanted to know if 8mb cards is the safest or if I can go higher also what happens when games have more than one save file per game? the difference between filesize afaik is 1000+ blocks free vs 257 blocks free if you could give an example of something that happens to cards above 8mb id appreciate it

**Comment by carnage702** [comment]
one doesnt have problems until it does and when it does it will corrupt everything.

if i recall if you use 16mb some games will not work like disc swap wont happen because you occupied too much ram with the memory card so the automatic disc swap will fail, the rest it depends on how much ram that game makes nintendont use.

**Comment by JordanB500** [comment]
in the case of corruption I have backups on my pc and I have the backups from my physical memory cards which I have not tampered with other than to do a full backup of both slot a and b and worse case scenario I can start over or use a save file off the internet. in your example you mention 16 mb what if i want to use 9-15 megabytes  instead (if it is possible to make one that size) or is it just untested because no one has tried it?

**Comment by carnage702** [comment]
> in the case of corruption I have backups on my pc and I have the backups from my physical memory cards which I have not tampered with other than to do a full backup of both slot a and b and worse case scenario I can start over or use a save file off the internet. in your example you mention 16 mb what if i want to use 9-15 megabytes instead (if it is possible to make one that size) or is it just untested because no one has tried it?

that doesnt work lol memory cards are certain sizes and games wouldnt recognize bad sizes gc memory cards come in blocks

59 blocks 512kb
251 blocks 2mb
1019 blocks 8mb

even 8mb already has some issues since games didnt expect it to be so big
https://ghostarchive.org/archive/HldJz

and if i recall slotb needs to be the smaller one like 59 blocks to work, not sure if slotb even works with anything bigger than 59 blocks tbh.

**Comment by JordanB500** [comment]
is there a reason for the file size on slot b? also I do not use the specific games that are listed in that link except for sonic adventure 2 battle but an incorrect display of available blocks is not much cause for concern. but thank you for the information

btw where do the bios files go do you put them in the app folder or what

**Comment by carnage702** [comment]
> is there a reason for the file size on slot b? also I do not use the specific games that are listed in that link except for sonic adventure 2 battle but an incorrect display of available blocks is not much cause for concern. but thank you for the information
> 
> btw where do the bios files go do you put them in the app folder or what

yes the reason is file size  available in the ram.

Nintendont needs ram too work and wii has very few ram and nintendont itself eats most of it so you are lucky we even have 8mb free that's why when we use 16mb some functions get interrupted because nintendont loose the ram it needs to work properly.
