### ISSUE TITLE
Trouble with exFAT

### ISSUE THREAD

**Issue by DanielArthurs** [FIX94/Nintendont#977]
I was reading about setting up a usb drive to use with nintendont and saw that ntfs was not supported and learned that a simple fix was to add a FAT32 partition to your usb drive. I was excited to do that and transferred all the files off of my drive so I could format it just to find out that my usb didn't support FAT32 it only had support for ntfs and exFAT. I went looking for any information on using the ntfs and quickly realized that it was never going to be supported, that's all fine and dandy because not too late after I read this "Nintendont runs best with storage devices formatted with 32 KB clusters. (Use either FAT32 or exFAT.)" I ended up formatting my usb to exFAT and made sure to alocate it to 32 kb instead of the default 128 kb. I transfered all my files back and inserted my usb, but to my dismay none of the games appeared and it didn't seem as if my wii didn't even register that I had a usb inserted, I reformatted it to ntfs so that I could use it for my wii games on usb loader gx can somebody help me or clarify where I went wrong, there doesn't seem to be a lot of information about exFAT usage with nintendont available.

**Comment by carnage702** [comment]
every usb supports fat32 you just need a formatter that isnt windows formatter since anything bigger than 64gb is antomatically only formated to exfat or ntfs.

Exfat was added through a pull request it wasnt the official devs that added so im not sure if it works even, never tryed, but if you really want good support for every homebrew on wii or wiiu you should just use fat32, bigger wii isos can be split and played in splited format using usbloader or wiiflow even.

**Comment by weirdal3333** [comment]
http://ridgecrop.co.uk/index.htm?guiformat.htm

Please close the issue after reading this page.
