### ISSUE TITLE
Wii CC doesen't work on Nintendont 

### ISSUE THREAD

**Issue by goldenBolado** [FIX94/Nintendont#981]
My CC works normally at the nintendont menu, but when I start any game the CC doesn't work and the 4 light of the wii remote is the only one on. I'm pretty sure that my cc and my wii remote are first party

**Comment by carnage702** [comment]
To make sure they are legit take a look at the screws

nintendo uses on all controllers triwing screws which means they only have 3 notches instead of regular screws who have 4

triwing
![221000587623_01381](https://user-images.githubusercontent.com/12446178/156423800-a84eb9b5-60c4-4cab-8534-b161918cf014.jpg)


Check both your wiimote and classic controller.

Nintendont has 2 bt modules one for menu and one for while ingame due to ram limitations, the one when playing games is much more compressed and smaller so it follows only key bt calls, that is why most fake/3rd party controllers dont work.

**Comment by goldenBolado** [comment]
> To make sure they are legit take a look at the screws
> 
> nintendo uses on all controllers triwing screws which means they only have 3 notches instead of regular screws who have 4
> 
> triwing ![221000587623_01381](https://user-images.githubusercontent.com/12446178/156423800-a84eb9b5-60c4-4cab-8534-b161918cf014.jpg)
> 
> Check both your wiimote and classic controller.
> 
> Nintendont has 2 bt modules one for menu and one for while ingame due to ram limitations, the one when playing games is much more compressed and smaller so it follows only key bt calls, that is why most fake/3rd party controllers dont work.

My cc is original but my wii remote is 3rd party, there is any way for me to play nintendont with a 3rd party controller?

**Comment by carnage702** [comment]
> > To make sure they are legit take a look at the screws
> > nintendo uses on all controllers triwing screws which means they only have 3 notches instead of regular screws who have 4
> > triwing ![221000587623_01381](https://user-images.githubusercontent.com/12446178/156423800-a84eb9b5-60c4-4cab-8534-b161918cf014.jpg)
> > Check both your wiimote and classic controller.
> > Nintendont has 2 bt modules one for menu and one for while ingame due to ram limitations, the one when playing games is much more compressed and smaller so it follows only key bt calls, that is why most fake/3rd party controllers dont work.
> 
> My cc is original but my wii remote is 3rd party, there is any way for me to play nintendont with a 3rd party controller?

its mostly luck what works works, what doesnt, doesnt work, get an official one.
