### ISSUE TITLE
Wrong clock on Zelda Wind Waker

### ISSUE THREAD

**Issue by lodgerz** [FIX94/Nintendont#997]
Hello, i have tried to run iso of Zelda Wind Waker with Nintendont. It works but savegame clock is wrong: it says we are in 2014.

If i use original Zelda DVD, savegame clock is correct. 
Why?
I use original gamecube memory card (no emulation).

**Comment by carnage702** [comment]
nintendont works in wii mode with wii clock speed 

Zelda calculates time by using a formula with cpu clock speed and of course it suposes you are on a gamecube therefore the calculations fail, but this is just a cosmetic issue it has no effect on the games themselves, savetime will also differ from using it on gc mode on the wii known as mios vs nintendont since the total savetime is also calculated this way.

To fix this you would need to find the game functions that each game uses and patch them to use wii clock speed on the formula which is different for each game, so no one bothered to adress this.

**Comment by GB-CG** [comment]
I can't reproduce this. Mine says 2022 with my memory card. Is your Wii date not set to 2022?
